/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;

/**
 * Identifies the type and organization of an aggregate. Section 6.2.5
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class AggregateType extends Object implements Serializable, Marshaller
{
   /** Grouping criterion used to group the aggregate. Enumeration from EBV document uid 206 */
   protected AggregateStateAggregateKind aggregateKind = AggregateStateAggregateKind.values()[0];

   /** Domain of entity (air, surface, subsurface, space, etc.) where zero means domain does not apply. uid 8 */
   protected PlatformDomain domain = PlatformDomain.values()[0];

   /** country to which the design of the entity is attributed uid 29 */
   protected Country country = Country.values()[0];

   /** category of entity 
   Value space: uint8 */
   protected int category;

   /** subcategory of entity uid 208 */
   protected AggregateStateSubcategory subcategory = AggregateStateSubcategory.values()[0];

   /** specific info based on subcategory field. specific is a reserved word in sql. uid 209 */
   protected AggregateStateSpecific specificInfo = AggregateStateSpecific.values()[0];

   /** extra is an undescribed parameter...
   Value space: uint8 */
   protected int extra;


/** Constructor creates and configures a new instance object */
 public AggregateType()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   if (aggregateKind != null)
       marshalSize += aggregateKind.getMarshalledSize();
   if (domain != null)
       marshalSize += domain.getMarshalledSize();
   if (country != null)
       marshalSize += country.getMarshalledSize();
   marshalSize += 1;  // category
   if (subcategory != null)
       marshalSize += subcategory.getMarshalledSize();
   if (specificInfo != null)
       marshalSize += specificInfo.getMarshalledSize();
   marshalSize += 1;  // extra

   return marshalSize;
}


/** Setter for {@link AggregateType#aggregateKind}
  * @param pAggregateKind new value of interest
  * @return same object to permit progressive setters */
public synchronized AggregateType setAggregateKind(AggregateStateAggregateKind pAggregateKind)
{
    aggregateKind = pAggregateKind;
    return this;
}
/** Getter for {@link AggregateType#aggregateKind}
  * @return value of interest */
public AggregateStateAggregateKind getAggregateKind()
{
    return aggregateKind; 
}

/** Setter for {@link AggregateType#domain}
  * @param pDomain new value of interest
  * @return same object to permit progressive setters */
public synchronized AggregateType setDomain(PlatformDomain pDomain)
{
    domain = pDomain;
    return this;
}
/** Getter for {@link AggregateType#domain}
  * @return value of interest */
public PlatformDomain getDomain()
{
    return domain; 
}

/** Setter for {@link AggregateType#country}
  * @param pCountry new value of interest
  * @return same object to permit progressive setters */
public synchronized AggregateType setCountry(Country pCountry)
{
    country = pCountry;
    return this;
}
/** Getter for {@link AggregateType#country}
  * @return value of interest */
public Country getCountry()
{
    return country; 
}

/** Setter for {@link AggregateType#category}
  * @param pCategory new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized AggregateType setCategory(int pCategory)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pCategory >= 0 && pCategory <= 255, "Value outside valid value space");
    category = pCategory;
    return this;
}
/** Getter for {@link AggregateType#category}
  * @return value of interest */
public int getCategory()
{
    return category; 
}

/** Setter for {@link AggregateType#subcategory}
  * @param pSubcategory new value of interest
  * @return same object to permit progressive setters */
public synchronized AggregateType setSubcategory(AggregateStateSubcategory pSubcategory)
{
    subcategory = pSubcategory;
    return this;
}
/** Getter for {@link AggregateType#subcategory}
  * @return value of interest */
public AggregateStateSubcategory getSubcategory()
{
    return subcategory; 
}

/** Setter for {@link AggregateType#specificInfo}
  * @param pSpecificInfo new value of interest
  * @return same object to permit progressive setters */
public synchronized AggregateType setSpecificInfo(AggregateStateSpecific pSpecificInfo)
{
    specificInfo = pSpecificInfo;
    return this;
}
/** Getter for {@link AggregateType#specificInfo}
  * @return value of interest */
public AggregateStateSpecific getSpecificInfo()
{
    return specificInfo; 
}

/** Setter for {@link AggregateType#extra}
  * @param pExtra new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized AggregateType setExtra(int pExtra)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pExtra >= 0 && pExtra <= 255, "Value outside valid value space");
    extra = pExtra;
    return this;
}
/** Getter for {@link AggregateType#extra}
  * @return value of interest */
public int getExtra()
{
    return extra; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{

    {
       aggregateKind.marshal(dos);
       domain.marshal(dos);
       country.marshal(dos);
       dos.writeByte((byte) category);
       subcategory.marshal(dos);
       specificInfo.marshal(dos);
       dos.writeByte((byte) extra);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;

    {
        aggregateKind = AggregateStateAggregateKind.unmarshalEnum(dis);
        uPosition += aggregateKind.getMarshalledSize();
        domain = PlatformDomain.unmarshalEnum(dis);
        uPosition += domain.getMarshalledSize();
        country = Country.unmarshalEnum(dis);
        uPosition += country.getMarshalledSize();
        category = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        subcategory = AggregateStateSubcategory.unmarshalEnum(dis);
        uPosition += subcategory.getMarshalledSize();
        specificInfo = AggregateStateSpecific.unmarshalEnum(dis);
        uPosition += specificInfo.getMarshalledSize();
        extra = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   aggregateKind.marshal(byteBuffer);
   domain.marshal(byteBuffer);
   country.marshal(byteBuffer);
   byteBuffer.put((byte) category);
   subcategory.marshal(byteBuffer);
   specificInfo.marshal(byteBuffer);
   byteBuffer.put((byte) extra);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    {
        aggregateKind = AggregateStateAggregateKind.unmarshalEnum(byteBuffer);
        domain = PlatformDomain.unmarshalEnum(byteBuffer);
        country = Country.unmarshalEnum(byteBuffer);
        category = Byte.toUnsignedInt(byteBuffer.get());
        subcategory = AggregateStateSubcategory.unmarshalEnum(byteBuffer);
        specificInfo = AggregateStateSpecific.unmarshalEnum(byteBuffer);
        extra = Byte.toUnsignedInt(byteBuffer.get());
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = new PduMap();

    map.put("aggregateKind", AggregateStateAggregateKind.unmarshalEnum(byteBuffer).getValue());
    map.put("domain", PlatformDomain.unmarshalEnum(byteBuffer).getValue());
    map.put("country", Country.unmarshalEnum(byteBuffer).getValue());
    map.put("category", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("subcategory", AggregateStateSubcategory.unmarshalEnum(byteBuffer).getValue());
    map.put("specificInfo", AggregateStateSpecific.unmarshalEnum(byteBuffer).getValue());
    map.put("extra", Byte.toUnsignedInt(byteBuffer.get()));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    AggregateStateAggregateKind.getEnumForValue(((Number) map.get("aggregateKind")).intValue()).marshal(byteBuffer);
    PlatformDomain.getEnumForValue(((Number) map.get("domain")).intValue()).marshal(byteBuffer);
    Country.getEnumForValue(((Number) map.get("country")).intValue()).marshal(byteBuffer);
    byteBuffer.put(((Number) map.get("category")).byteValue());
    AggregateStateSubcategory.getEnumForValue(((Number) map.get("subcategory")).intValue()).marshal(byteBuffer);
    AggregateStateSpecific.getEnumForValue(((Number) map.get("specificInfo")).intValue()).marshal(byteBuffer);
    byteBuffer.put(((Number) map.get("extra")).byteValue());
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += AggregateStateAggregateKind.getEnumForValue(((Number) map.get("aggregateKind")).intValue()).getMarshalledSize();
    marshalSize += PlatformDomain.getEnumForValue(((Number) map.get("domain")).intValue()).getMarshalledSize();
    marshalSize += Country.getEnumForValue(((Number) map.get("country")).intValue()).getMarshalledSize();
    marshalSize += 1;  // category
    marshalSize += AggregateStateSubcategory.getEnumForValue(((Number) map.get("subcategory")).intValue()).getMarshalledSize();
    marshalSize += AggregateStateSpecific.getEnumForValue(((Number) map.get("specificInfo")).intValue()).getMarshalledSize();
    marshalSize += 1;  // extra

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

 /**
  * Compare all fields that contribute to the state, ignoring
  * transient and static fields, for <code>this</code> and the supplied object
  * @param obj the object to compare to
  * @return true if the objects are equal, false otherwise.
  */
 public synchronized boolean equalsImpl(Object obj)
 {
     final AggregateType rhs = (AggregateType)obj;

     if( ! (aggregateKind == rhs.aggregateKind)) return false;
     if( ! (domain == rhs.domain)) return false;
     if( ! (country == rhs.country)) return false;
     if( ! (category == rhs.category)) return false;
     if( ! (subcategory == rhs.subcategory)) return false;
     if( ! (specificInfo == rhs.specificInfo)) return false;
     if( ! (extra == rhs.extra)) return false;
    return true;
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" aggregateKind:").append(aggregateKind); // writeOneToString
    sb.append(" domain:").append(domain); // writeOneToString
    sb.append(" country:").append(country); // writeOneToString
    sb.append(" category:").append(category); // writeOneToString
    sb.append(" subcategory:").append(subcategory); // writeOneToString
    sb.append(" specificInfo:").append(specificInfo); // writeOneToString
    sb.append(" extra:").append(extra); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.aggregateKind,
	                     this.domain,
	                     this.country,
	                     this.category,
	                     this.subcategory,
	                     this.specificInfo,
	                     this.extra);
 }
} // end of AggregateType
