/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;
import java.nio.ByteBuffer;

/**
 * Section 7.5.9. A request for data from an entity shall be communicated by issuing a Data Query PDU. See 5.6.5.9
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class DataQueryPdu extends SimulationManagementFamilyPdu implements Serializable, Marshaller
{

   /** The name of this PDU type */
   public static final String NAME = "DataQueryPdu";
   
   /** ID of request 
   Value space: uint32 */
   protected UnsignedInteger requestID = UnsignedInteger.ZERO;

   /** time issues between issues of Data PDUs. Zero means send once only. 
   Value space: uint32 */
   protected UnsignedInteger timeInterval = UnsignedInteger.ZERO;

   /** Number of fixed datum records 
   Value space: uint32 */
   protected UnsignedInteger numberOfFixedDatumRecords = UnsignedInteger.ZERO;

   /** Number of variable datum records, handled automatically by marshaller at run time (and not modifiable by end-user programmers) 
   Value space: uint32 */
   protected UnsignedInteger numberOfVariableDatumRecords = UnsignedInteger.ZERO;

   /** variable length list of fixed datums */
   protected List< FixedDatum > fixedDatums = new ArrayList<>();
 
   /** variable length list of variable length datums */
   protected List< VariableDatum > variableDatums = new ArrayList<>();
 

/** Constructor creates and configures a new instance object */
 public DataQueryPdu()
 {
    setPduType( DisPduType.DATA_QUERY );
 }
/** copy method creates a deep copy of current object using preferred marshalling method
 * @return deep copy of PDU */
 public synchronized DataQueryPdu copy()
 {
     return copyDataOutputStream();
 }
/** Creates a "deep copy" of current object using ByteBuffer methods.
 * @return deep copy of PDU */
 public synchronized DataQueryPdu copyByteBuffer()
 {
     DataQueryPdu newCopy = new DataQueryPdu();
     ByteBuffer byteBuffer = ByteBuffer.allocate(400);
     try
     {
         this.marshal(byteBuffer);      // working
         newCopy.unmarshal(byteBuffer); // not working
     }
     catch (Exception e)
     {
         System.err.println("DataQueryPdu deep copy() marshall/unmarshall ByteBuffer exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
     return newCopy;
 }

/** byteArrayOutputStream (baos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
/** dataOutputStream (dos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected DataOutputStream      dataOutputStream      = new DataOutputStream(byteArrayOutputStream);

/** copy method creates a deep copy of current object using DataOutputStream methods.
 * @return deep copy of PDU */
 public synchronized DataQueryPdu copyDataOutputStream()
 {
     DataQueryPdu newCopy = new DataQueryPdu();
     try
     {
         this.marshal(dataOutputStream);
         byte[] byteArrayDOS = byteArrayOutputStream.toByteArray();
         newCopy.unmarshal(ByteBuffer.wrap(byteArrayDOS));
     }
     catch (Exception e)
     {
         System.err.println("DataQueryPdu deep copy() marshall/unmarshall DataOutputStream exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
        try
        {
                 dataOutputStream.flush();
            byteArrayOutputStream.flush();
            byteArrayOutputStream.reset();
        }
        catch (IOException ioe)
        {
            System.err.println("DataQueryPdu copyDataOutputStream() flush IOException: " + ioe.getMessage());
        }
     return newCopy;
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   marshalSize += 4;  // requestID
   marshalSize += 4;  // timeInterval
   marshalSize += 4;  // numberOfFixedDatumRecords
   marshalSize += 4;  // numberOfVariableDatumRecords
   if (fixedDatums != null)
       for (int idx=0; idx < fixedDatums.size(); idx++)
       {
            FixedDatum listElement = fixedDatums.get(idx);
            marshalSize += listElement.getMarshalledSize();
       }
   if (variableDatums != null)
       for (int idx=0; idx < variableDatums.size(); idx++)
       {
            VariableDatum listElement = variableDatums.get(idx);
            marshalSize += listElement.getMarshalledSize();
       }

   return marshalSize;
}


/** Setter for {@link DataQueryPdu#requestID}
  * @param pRequestID new value of interest. Value space uint32
  * @return same object to permit progressive setters */
public synchronized DataQueryPdu setRequestID(UnsignedInteger pRequestID)
{
    requestID = pRequestID;
    return this;
}
/** Getter for {@link DataQueryPdu#requestID}
  * @return value of interest */
public UnsignedInteger getRequestID()
{
    return requestID; 
}

/** Setter for {@link DataQueryPdu#timeInterval}
  * @param pTimeInterval new value of interest. Value space uint32
  * @return same object to permit progressive setters */
public synchronized DataQueryPdu setTimeInterval(UnsignedInteger pTimeInterval)
{
    timeInterval = pTimeInterval;
    return this;
}
/** Getter for {@link DataQueryPdu#timeInterval}
  * @return value of interest */
public UnsignedInteger getTimeInterval()
{
    return timeInterval; 
}

/** Setter for {@link DataQueryPdu#fixedDatums}
  * @param pFixedDatums new value of interest
  * @return same object to permit progressive setters */
public synchronized DataQueryPdu setFixedDatums(List<FixedDatum> pFixedDatums)
{
    fixedDatums = pFixedDatums;
    return this;
}
/** Getter for {@link DataQueryPdu#fixedDatums}
  * @return value of interest */
public List<FixedDatum> getFixedDatums()
{
    return fixedDatums; 
}

/** Setter for {@link DataQueryPdu#variableDatums}
  * @param pVariableDatums new value of interest
  * @return same object to permit progressive setters */
public synchronized DataQueryPdu setVariableDatums(List<VariableDatum> pVariableDatums)
{
    variableDatums = pVariableDatums;
    return this;
}
/** Getter for {@link DataQueryPdu#variableDatums}
  * @return value of interest */
public List<VariableDatum> getVariableDatums()
{
    return variableDatums; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    super.marshal(dos);

    {
       dos.writeInt(requestID.intValue());
       dos.writeInt(timeInterval.intValue());
       dos.writeInt(fixedDatums.size());
       dos.writeInt(variableDatums.size());

       for (int idx = 0; idx < fixedDatums.size(); idx++)
       {
            FixedDatum aFixedDatum = fixedDatums.get(idx);
            aFixedDatum.marshal(dos);
       }


       for (int idx = 0; idx < variableDatums.size(); idx++)
       {
            VariableDatum aVariableDatum = variableDatums.get(idx);
            aVariableDatum.marshal(dos);
       }

    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    uPosition += super.unmarshal(dis);


    {
        requestID = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
        timeInterval = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
        numberOfFixedDatumRecords = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
        numberOfVariableDatumRecords = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
        for (int idx = 0; idx < ((Number) numberOfFixedDatumRecords).intValue(); idx++)
        {
            FixedDatum anX = new FixedDatum();
            uPosition += anX.unmarshal(dis);
            fixedDatums.add(anX);
        }

        for (int idx = 0; idx < ((Number) numberOfVariableDatumRecords).intValue(); idx++)
        {
            VariableDatum anX = new VariableDatum();
            uPosition += anX.unmarshal(dis);
            variableDatums.add(anX);
        }

    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   super.marshal(byteBuffer);
   byteBuffer.putInt(requestID.intValue());
   byteBuffer.putInt(timeInterval.intValue());
   byteBuffer.putInt( (int)fixedDatums.size());
   byteBuffer.putInt( (int)variableDatums.size());

   for (int idx = 0; idx < fixedDatums.size(); idx++)
   {
        FixedDatum aFixedDatum = fixedDatums.get(idx);
        aFixedDatum.marshal(byteBuffer);
   }


   for (int idx = 0; idx < variableDatums.size(); idx++)
   {
        VariableDatum aVariableDatum = variableDatums.get(idx);
        aVariableDatum.marshal(byteBuffer);
   }

}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    super.unmarshal(byteBuffer);

    {
        requestID = UnsignedInteger.fromIntBits(byteBuffer.getInt());
        timeInterval = UnsignedInteger.fromIntBits(byteBuffer.getInt());
        numberOfFixedDatumRecords = UnsignedInteger.fromIntBits(byteBuffer.getInt());
        numberOfVariableDatumRecords = UnsignedInteger.fromIntBits(byteBuffer.getInt());
        for (int idx = 0; idx < ((Number) numberOfFixedDatumRecords).intValue(); idx++)
        {
            FixedDatum anX = new FixedDatum();
            anX.unmarshal(byteBuffer);
            fixedDatums.add(anX);
        }

        for (int idx = 0; idx < ((Number) numberOfVariableDatumRecords).intValue(); idx++)
        {
            VariableDatum anX = new VariableDatum();
            anX.unmarshal(byteBuffer);
            variableDatums.add(anX);
        }

    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = SimulationManagementFamilyPdu.fromBufferToMap(byteBuffer);

    map.put("requestID", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    map.put("timeInterval", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    map.put("numberOfFixedDatumRecords", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    map.put("numberOfVariableDatumRecords", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    List fixedDatums = new ArrayList<>();
    for (int idx = 0; idx < ((Number) map.get("numberOfFixedDatumRecords")).intValue(); idx++)
    {
        fixedDatums.add(FixedDatum.fromBufferToMap(byteBuffer));
    }
    map.put("fixedDatums", fixedDatums);

    List variableDatums = new ArrayList<>();
    for (int idx = 0; idx < ((Number) map.get("numberOfVariableDatumRecords")).intValue(); idx++)
    {
        variableDatums.add(VariableDatum.fromBufferToMap(byteBuffer));
    }
    map.put("variableDatums", variableDatums);

    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    SimulationManagementFamilyPdu.fromMapToBuffer(map, byteBuffer);
    byteBuffer.putInt(((Number) map.get("requestID")).intValue());
    byteBuffer.putInt(((Number) map.get("timeInterval")).intValue());
    byteBuffer.putInt(((Number) map.get("numberOfFixedDatumRecords")).intValue());
    byteBuffer.putInt(((Number) map.get("numberOfVariableDatumRecords")).intValue());

    List fixedDatums = (List) map.get("fixedDatums");
    for (int idx = 0; idx < ((Number) map.get("numberOfFixedDatumRecords")).intValue(); idx++)
    {
        FixedDatum.fromMapToBuffer((PduMap) fixedDatums.get(idx), byteBuffer);
    }


    List variableDatums = (List) map.get("variableDatums");
    for (int idx = 0; idx < ((Number) map.get("numberOfVariableDatumRecords")).intValue(); idx++)
    {
        VariableDatum.fromMapToBuffer((PduMap) variableDatums.get(idx), byteBuffer);
    }

}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += SimulationManagementFamilyPdu.getMarshalledSize(map);
    marshalSize += 4;  // requestID
    marshalSize += 4;  // timeInterval
    marshalSize += 4;  // numberOfFixedDatumRecords
    marshalSize += 4;  // numberOfVariableDatumRecords
    List fixedDatums = (List) map.get("fixedDatums");
    for (int idx = 0; idx < ((Number) map.get("numberOfFixedDatumRecords")).intValue(); idx++)
        marshalSize += FixedDatum.getMarshalledSize((PduMap) fixedDatums.get(idx));
    List variableDatums = (List) map.get("variableDatums");
    for (int idx = 0; idx < ((Number) map.get("numberOfVariableDatumRecords")).intValue(); idx++)
        marshalSize += VariableDatum.getMarshalledSize((PduMap) variableDatums.get(idx));

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public synchronized boolean equalsImpl(Object obj)
 {
     final DataQueryPdu rhs = (DataQueryPdu)obj;

     if( ! (requestID == rhs.requestID)) return false;
     if( ! (timeInterval == rhs.timeInterval)) return false;
     if( ! Objects.equals(fixedDatums, rhs.fixedDatums) ) return false;
     if( ! Objects.equals(variableDatums, rhs.variableDatums) ) return false;
    return super.equalsImpl(rhs);
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(super.toString());
    sb.append(" requestID:").append(requestID); // writeOneToString
    sb.append(" timeInterval:").append(timeInterval); // writeOneToString
    sb.append(" fixedDatums: ");
    fixedDatums.forEach(r->{ sb2.append(" ").append(r);}); // writeList
    sb.append(sb2.toString().trim());
    // https://stackoverflow.com/questions/2242471/clearing-a-string-buffer-builder-after-loop
    sb2.setLength(0); // reset
    sb.append(" variableDatums: ");
    variableDatums.forEach(r->{ sb2.append(" ").append(r);}); // writeList
    sb.append(sb2.toString().trim());
    // https://stackoverflow.com/questions/2242471/clearing-a-string-buffer-builder-after-loop
    sb2.setLength(0); // reset

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.requestID,
	                     this.timeInterval,
	                     this.numberOfFixedDatumRecords,
	                     this.numberOfVariableDatumRecords,
	                     this.fixedDatums,
	                     this.variableDatums);
 }
} // end of DataQueryPdu
