/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;

/**
 * Association or disassociation of two entities.  Section 6.2.94.4.3
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class EntityAssociationVP extends Object implements Serializable, Marshaller
{
   /** The identification of the Variable Parameter record. Enumeration from EBV uid 56 */
   protected VariableParameterRecordType recordType = VariableParameterRecordType.ENTITY_ASSOCIATION;

   /** Indicates if this VP has changed since last issuance uid 320 */
   protected EntityVPRecordChangeIndicator changeIndicator = EntityVPRecordChangeIndicator.values()[0];

   /** Indicates association status between two entities uid 319 */
   protected EntityAssociationAssociationType associationStatus = EntityAssociationAssociationType.values()[0];

   /** Type of association; 8-bit enum uid 323 */
   protected EntityAssociationPhysicalAssociationType associationType = EntityAssociationPhysicalAssociationType.values()[0];

   /** Object ID of entity associated with this entity */
   protected EntityID  entityID = new EntityID(); 

   /** Station location on one's own entity uid 212 */
   protected IsPartOfStationName ownStationLocation = IsPartOfStationName.values()[0];

   /** Type of physical connection uid 324 */
   protected EntityAssociationPhysicalConnectionType physicalConnectionType = EntityAssociationPhysicalConnectionType.values()[0];

   /** Type of member the entity is within the group uid 321 */
   protected EntityAssociationGroupMemberType groupMemberType = EntityAssociationGroupMemberType.values()[0];

   /** Group if any to which the entity belongs 
   Value space: uint16 */
   protected int groupNumber;


/** Constructor creates and configures a new instance object */
 public EntityAssociationVP()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   if (recordType != null)
       marshalSize += recordType.getMarshalledSize();
   if (changeIndicator != null)
       marshalSize += changeIndicator.getMarshalledSize();
   if (associationStatus != null)
       marshalSize += associationStatus.getMarshalledSize();
   if (associationType != null)
       marshalSize += associationType.getMarshalledSize();
   if (entityID != null)
       marshalSize += entityID.getMarshalledSize();
   if (ownStationLocation != null)
       marshalSize += ownStationLocation.getMarshalledSize();
   if (physicalConnectionType != null)
       marshalSize += physicalConnectionType.getMarshalledSize();
   if (groupMemberType != null)
       marshalSize += groupMemberType.getMarshalledSize();
   marshalSize += 2;  // groupNumber

   return marshalSize;
}


/** Setter for {@link EntityAssociationVP#recordType}
  * @param pRecordType new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setRecordType(VariableParameterRecordType pRecordType)
{
    recordType = pRecordType;
    return this;
}
/** Getter for {@link EntityAssociationVP#recordType}
  * @return value of interest */
public VariableParameterRecordType getRecordType()
{
    return recordType; 
}

/** Setter for {@link EntityAssociationVP#changeIndicator}
  * @param pChangeIndicator new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setChangeIndicator(EntityVPRecordChangeIndicator pChangeIndicator)
{
    changeIndicator = pChangeIndicator;
    return this;
}
/** Getter for {@link EntityAssociationVP#changeIndicator}
  * @return value of interest */
public EntityVPRecordChangeIndicator getChangeIndicator()
{
    return changeIndicator; 
}

/** Setter for {@link EntityAssociationVP#associationStatus}
  * @param pAssociationStatus new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setAssociationStatus(EntityAssociationAssociationType pAssociationStatus)
{
    associationStatus = pAssociationStatus;
    return this;
}
/** Getter for {@link EntityAssociationVP#associationStatus}
  * @return value of interest */
public EntityAssociationAssociationType getAssociationStatus()
{
    return associationStatus; 
}

/** Setter for {@link EntityAssociationVP#associationType}
  * @param pAssociationType new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setAssociationType(EntityAssociationPhysicalAssociationType pAssociationType)
{
    associationType = pAssociationType;
    return this;
}
/** Getter for {@link EntityAssociationVP#associationType}
  * @return value of interest */
public EntityAssociationPhysicalAssociationType getAssociationType()
{
    return associationType; 
}

/** Setter for {@link EntityAssociationVP#entityID}
  * @param pEntityID new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setEntityID(EntityID pEntityID)
{
    entityID = pEntityID;
    return this;
}
/** Getter for {@link EntityAssociationVP#entityID}
  * @return value of interest */
public EntityID getEntityID()
{
    return entityID;
}


/** Setter for {@link EntityAssociationVP#ownStationLocation}
  * @param pOwnStationLocation new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setOwnStationLocation(IsPartOfStationName pOwnStationLocation)
{
    ownStationLocation = pOwnStationLocation;
    return this;
}
/** Getter for {@link EntityAssociationVP#ownStationLocation}
  * @return value of interest */
public IsPartOfStationName getOwnStationLocation()
{
    return ownStationLocation; 
}

/** Setter for {@link EntityAssociationVP#physicalConnectionType}
  * @param pPhysicalConnectionType new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setPhysicalConnectionType(EntityAssociationPhysicalConnectionType pPhysicalConnectionType)
{
    physicalConnectionType = pPhysicalConnectionType;
    return this;
}
/** Getter for {@link EntityAssociationVP#physicalConnectionType}
  * @return value of interest */
public EntityAssociationPhysicalConnectionType getPhysicalConnectionType()
{
    return physicalConnectionType; 
}

/** Setter for {@link EntityAssociationVP#groupMemberType}
  * @param pGroupMemberType new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setGroupMemberType(EntityAssociationGroupMemberType pGroupMemberType)
{
    groupMemberType = pGroupMemberType;
    return this;
}
/** Getter for {@link EntityAssociationVP#groupMemberType}
  * @return value of interest */
public EntityAssociationGroupMemberType getGroupMemberType()
{
    return groupMemberType; 
}

/** Setter for {@link EntityAssociationVP#groupNumber}
  * @param pGroupNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized EntityAssociationVP setGroupNumber(int pGroupNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pGroupNumber >= 0 && pGroupNumber <= 65535, "Value outside valid value space");
    groupNumber = pGroupNumber;
    return this;
}
/** Getter for {@link EntityAssociationVP#groupNumber}
  * @return value of interest */
public int getGroupNumber()
{
    return groupNumber; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{

    {
       recordType.marshal(dos);
       changeIndicator.marshal(dos);
       associationStatus.marshal(dos);
       associationType.marshal(dos);
       entityID.marshal(dos);
       ownStationLocation.marshal(dos);
       physicalConnectionType.marshal(dos);
       groupMemberType.marshal(dos);
       dos.writeShort((short) groupNumber);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;

    {
        recordType = VariableParameterRecordType.unmarshalEnum(dis);
        uPosition += recordType.getMarshalledSize();
        changeIndicator = EntityVPRecordChangeIndicator.unmarshalEnum(dis);
        uPosition += changeIndicator.getMarshalledSize();
        associationStatus = EntityAssociationAssociationType.unmarshalEnum(dis);
        uPosition += associationStatus.getMarshalledSize();
        associationType = EntityAssociationPhysicalAssociationType.unmarshalEnum(dis);
        uPosition += associationType.getMarshalledSize();
        uPosition += entityID.unmarshal(dis);
        ownStationLocation = IsPartOfStationName.unmarshalEnum(dis);
        uPosition += ownStationLocation.getMarshalledSize();
        physicalConnectionType = EntityAssociationPhysicalConnectionType.unmarshalEnum(dis);
        uPosition += physicalConnectionType.getMarshalledSize();
        groupMemberType = EntityAssociationGroupMemberType.unmarshalEnum(dis);
        uPosition += groupMemberType.getMarshalledSize();
        groupNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   recordType.marshal(byteBuffer);
   changeIndicator.marshal(byteBuffer);
   associationStatus.marshal(byteBuffer);
   associationType.marshal(byteBuffer);
   entityID.marshal(byteBuffer);
   ownStationLocation.marshal(byteBuffer);
   physicalConnectionType.marshal(byteBuffer);
   groupMemberType.marshal(byteBuffer);
   byteBuffer.putShort((short) groupNumber);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    {
        recordType = VariableParameterRecordType.unmarshalEnum(byteBuffer);
        changeIndicator = EntityVPRecordChangeIndicator.unmarshalEnum(byteBuffer);
        associationStatus = EntityAssociationAssociationType.unmarshalEnum(byteBuffer);
        associationType = EntityAssociationPhysicalAssociationType.unmarshalEnum(byteBuffer);
        entityID.unmarshal(byteBuffer);
        ownStationLocation = IsPartOfStationName.unmarshalEnum(byteBuffer);
        physicalConnectionType = EntityAssociationPhysicalConnectionType.unmarshalEnum(byteBuffer);
        groupMemberType = EntityAssociationGroupMemberType.unmarshalEnum(byteBuffer);
        groupNumber = Short.toUnsignedInt(byteBuffer.getShort());
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = new PduMap();

    map.put("recordType", VariableParameterRecordType.unmarshalEnum(byteBuffer).getValue());
    map.put("changeIndicator", EntityVPRecordChangeIndicator.unmarshalEnum(byteBuffer).getValue());
    map.put("associationStatus", EntityAssociationAssociationType.unmarshalEnum(byteBuffer).getValue());
    map.put("associationType", EntityAssociationPhysicalAssociationType.unmarshalEnum(byteBuffer).getValue());
    map.put("entityID", EntityID.fromBufferToMap(byteBuffer));
    map.put("ownStationLocation", IsPartOfStationName.unmarshalEnum(byteBuffer).getValue());
    map.put("physicalConnectionType", EntityAssociationPhysicalConnectionType.unmarshalEnum(byteBuffer).getValue());
    map.put("groupMemberType", EntityAssociationGroupMemberType.unmarshalEnum(byteBuffer).getValue());
    map.put("groupNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    VariableParameterRecordType.getEnumForValue(((Number) map.get("recordType")).intValue()).marshal(byteBuffer);
    EntityVPRecordChangeIndicator.getEnumForValue(((Number) map.get("changeIndicator")).intValue()).marshal(byteBuffer);
    EntityAssociationAssociationType.getEnumForValue(((Number) map.get("associationStatus")).intValue()).marshal(byteBuffer);
    EntityAssociationPhysicalAssociationType.getEnumForValue(((Number) map.get("associationType")).intValue()).marshal(byteBuffer);
    EntityID.fromMapToBuffer((PduMap) map.get("entityID"), byteBuffer);
    IsPartOfStationName.getEnumForValue(((Number) map.get("ownStationLocation")).intValue()).marshal(byteBuffer);
    EntityAssociationPhysicalConnectionType.getEnumForValue(((Number) map.get("physicalConnectionType")).intValue()).marshal(byteBuffer);
    EntityAssociationGroupMemberType.getEnumForValue(((Number) map.get("groupMemberType")).intValue()).marshal(byteBuffer);
    byteBuffer.putShort(((Number) map.get("groupNumber")).shortValue());
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += VariableParameterRecordType.getEnumForValue(((Number) map.get("recordType")).intValue()).getMarshalledSize();
    marshalSize += EntityVPRecordChangeIndicator.getEnumForValue(((Number) map.get("changeIndicator")).intValue()).getMarshalledSize();
    marshalSize += EntityAssociationAssociationType.getEnumForValue(((Number) map.get("associationStatus")).intValue()).getMarshalledSize();
    marshalSize += EntityAssociationPhysicalAssociationType.getEnumForValue(((Number) map.get("associationType")).intValue()).getMarshalledSize();
    marshalSize += EntityID.getMarshalledSize((PduMap) map.get("entityID"));
    marshalSize += IsPartOfStationName.getEnumForValue(((Number) map.get("ownStationLocation")).intValue()).getMarshalledSize();
    marshalSize += EntityAssociationPhysicalConnectionType.getEnumForValue(((Number) map.get("physicalConnectionType")).intValue()).getMarshalledSize();
    marshalSize += EntityAssociationGroupMemberType.getEnumForValue(((Number) map.get("groupMemberType")).intValue()).getMarshalledSize();
    marshalSize += 2;  // groupNumber

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

 /**
  * Compare all fields that contribute to the state, ignoring
  * transient and static fields, for <code>this</code> and the supplied object
  * @param obj the object to compare to
  * @return true if the objects are equal, false otherwise.
  */
 public synchronized boolean equalsImpl(Object obj)
 {
     final EntityAssociationVP rhs = (EntityAssociationVP)obj;

     if( ! (recordType == rhs.recordType)) return false;
     if( ! (changeIndicator == rhs.changeIndicator)) return false;
     if( ! (associationStatus == rhs.associationStatus)) return false;
     if( ! (associationType == rhs.associationType)) return false;
     if( ! Objects.equals(entityID, rhs.entityID) ) return false;
     if( ! (ownStationLocation == rhs.ownStationLocation)) return false;
     if( ! (physicalConnectionType == rhs.physicalConnectionType)) return false;
     if( ! (groupMemberType == rhs.groupMemberType)) return false;
     if( ! (groupNumber == rhs.groupNumber)) return false;
    return true;
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" recordType:").append(recordType); // writeOneToString
    sb.append(" changeIndicator:").append(changeIndicator); // writeOneToString
    sb.append(" associationStatus:").append(associationStatus); // writeOneToString
    sb.append(" associationType:").append(associationType); // writeOneToString
    sb.append(" entityID:").append(entityID); // writeOneToString
    sb.append(" ownStationLocation:").append(ownStationLocation); // writeOneToString
    sb.append(" physicalConnectionType:").append(physicalConnectionType); // writeOneToString
    sb.append(" groupMemberType:").append(groupMemberType); // writeOneToString
    sb.append(" groupNumber:").append(groupNumber); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.recordType,
	                     this.changeIndicator,
	                     this.associationStatus,
	                     this.associationType,
	                     this.entityID,
	                     this.ownStationLocation,
	                     this.physicalConnectionType,
	                     this.groupMemberType,
	                     this.groupNumber);
 }
} // end of EntityAssociationVP
