/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;

/**
 * Basic operational data for IFF. Section 6.2.39
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class FundamentalOperationalData extends Object implements Serializable, Marshaller
{
   /** system status, IEEE DIS 7 defined 
   Value space: uint8 */
   protected int systemStatus;

   /** data field 1 
   Value space: uint8 */
   protected int dataField1;

   /** eight boolean fields 
   Value space: uint8 */
   protected int informationLayers;

   /** enumeration 
   Value space: uint8 */
   protected int dataField2;

   /** parameter, enumeration 
   Value space: uint16 */
   protected int parameter1;

   /** parameter, enumeration 
   Value space: uint16 */
   protected int parameter2;

   /** parameter, enumeration 
   Value space: uint16 */
   protected int parameter3;

   /** parameter, enumeration 
   Value space: uint16 */
   protected int parameter4;

   /** parameter, enumeration 
   Value space: uint16 */
   protected int parameter5;

   /** parameter, enumeration 
   Value space: uint16 */
   protected int parameter6;


/** Constructor creates and configures a new instance object */
 public FundamentalOperationalData()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize += 1;  // systemStatus
   marshalSize += 1;  // dataField1
   marshalSize += 1;  // informationLayers
   marshalSize += 1;  // dataField2
   marshalSize += 2;  // parameter1
   marshalSize += 2;  // parameter2
   marshalSize += 2;  // parameter3
   marshalSize += 2;  // parameter4
   marshalSize += 2;  // parameter5
   marshalSize += 2;  // parameter6

   return marshalSize;
}


/** Setter for {@link FundamentalOperationalData#systemStatus}
  * @param pSystemStatus new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setSystemStatus(int pSystemStatus)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pSystemStatus >= 0 && pSystemStatus <= 255, "Value outside valid value space");
    systemStatus = pSystemStatus;
    return this;
}
/** Getter for {@link FundamentalOperationalData#systemStatus}
  * @return value of interest */
public int getSystemStatus()
{
    return systemStatus; 
}

/** Setter for {@link FundamentalOperationalData#dataField1}
  * @param pDataField1 new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setDataField1(int pDataField1)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pDataField1 >= 0 && pDataField1 <= 255, "Value outside valid value space");
    dataField1 = pDataField1;
    return this;
}
/** Getter for {@link FundamentalOperationalData#dataField1}
  * @return value of interest */
public int getDataField1()
{
    return dataField1; 
}

/** Setter for {@link FundamentalOperationalData#informationLayers}
  * @param pInformationLayers new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setInformationLayers(int pInformationLayers)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pInformationLayers >= 0 && pInformationLayers <= 255, "Value outside valid value space");
    informationLayers = pInformationLayers;
    return this;
}
/** Getter for {@link FundamentalOperationalData#informationLayers}
  * @return value of interest */
public int getInformationLayers()
{
    return informationLayers; 
}

/** Setter for {@link FundamentalOperationalData#dataField2}
  * @param pDataField2 new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setDataField2(int pDataField2)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pDataField2 >= 0 && pDataField2 <= 255, "Value outside valid value space");
    dataField2 = pDataField2;
    return this;
}
/** Getter for {@link FundamentalOperationalData#dataField2}
  * @return value of interest */
public int getDataField2()
{
    return dataField2; 
}

/** Setter for {@link FundamentalOperationalData#parameter1}
  * @param pParameter1 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setParameter1(int pParameter1)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pParameter1 >= 0 && pParameter1 <= 65535, "Value outside valid value space");
    parameter1 = pParameter1;
    return this;
}
/** Getter for {@link FundamentalOperationalData#parameter1}
  * @return value of interest */
public int getParameter1()
{
    return parameter1; 
}

/** Setter for {@link FundamentalOperationalData#parameter2}
  * @param pParameter2 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setParameter2(int pParameter2)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pParameter2 >= 0 && pParameter2 <= 65535, "Value outside valid value space");
    parameter2 = pParameter2;
    return this;
}
/** Getter for {@link FundamentalOperationalData#parameter2}
  * @return value of interest */
public int getParameter2()
{
    return parameter2; 
}

/** Setter for {@link FundamentalOperationalData#parameter3}
  * @param pParameter3 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setParameter3(int pParameter3)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pParameter3 >= 0 && pParameter3 <= 65535, "Value outside valid value space");
    parameter3 = pParameter3;
    return this;
}
/** Getter for {@link FundamentalOperationalData#parameter3}
  * @return value of interest */
public int getParameter3()
{
    return parameter3; 
}

/** Setter for {@link FundamentalOperationalData#parameter4}
  * @param pParameter4 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setParameter4(int pParameter4)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pParameter4 >= 0 && pParameter4 <= 65535, "Value outside valid value space");
    parameter4 = pParameter4;
    return this;
}
/** Getter for {@link FundamentalOperationalData#parameter4}
  * @return value of interest */
public int getParameter4()
{
    return parameter4; 
}

/** Setter for {@link FundamentalOperationalData#parameter5}
  * @param pParameter5 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setParameter5(int pParameter5)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pParameter5 >= 0 && pParameter5 <= 65535, "Value outside valid value space");
    parameter5 = pParameter5;
    return this;
}
/** Getter for {@link FundamentalOperationalData#parameter5}
  * @return value of interest */
public int getParameter5()
{
    return parameter5; 
}

/** Setter for {@link FundamentalOperationalData#parameter6}
  * @param pParameter6 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized FundamentalOperationalData setParameter6(int pParameter6)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pParameter6 >= 0 && pParameter6 <= 65535, "Value outside valid value space");
    parameter6 = pParameter6;
    return this;
}
/** Getter for {@link FundamentalOperationalData#parameter6}
  * @return value of interest */
public int getParameter6()
{
    return parameter6; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{

    {
       dos.writeByte((byte) systemStatus);
       dos.writeByte((byte) dataField1);
       dos.writeByte((byte) informationLayers);
       dos.writeByte((byte) dataField2);
       dos.writeShort((short) parameter1);
       dos.writeShort((short) parameter2);
       dos.writeShort((short) parameter3);
       dos.writeShort((short) parameter4);
       dos.writeShort((short) parameter5);
       dos.writeShort((short) parameter6);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;

    {
        systemStatus = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        dataField1 = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        informationLayers = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        dataField2 = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        parameter1 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        parameter2 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        parameter3 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        parameter4 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        parameter5 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        parameter6 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   byteBuffer.put((byte) systemStatus);
   byteBuffer.put((byte) dataField1);
   byteBuffer.put((byte) informationLayers);
   byteBuffer.put((byte) dataField2);
   byteBuffer.putShort((short) parameter1);
   byteBuffer.putShort((short) parameter2);
   byteBuffer.putShort((short) parameter3);
   byteBuffer.putShort((short) parameter4);
   byteBuffer.putShort((short) parameter5);
   byteBuffer.putShort((short) parameter6);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    {
        systemStatus = Byte.toUnsignedInt(byteBuffer.get());
        dataField1 = Byte.toUnsignedInt(byteBuffer.get());
        informationLayers = Byte.toUnsignedInt(byteBuffer.get());
        dataField2 = Byte.toUnsignedInt(byteBuffer.get());
        parameter1 = Short.toUnsignedInt(byteBuffer.getShort());
        parameter2 = Short.toUnsignedInt(byteBuffer.getShort());
        parameter3 = Short.toUnsignedInt(byteBuffer.getShort());
        parameter4 = Short.toUnsignedInt(byteBuffer.getShort());
        parameter5 = Short.toUnsignedInt(byteBuffer.getShort());
        parameter6 = Short.toUnsignedInt(byteBuffer.getShort());
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = new PduMap();

    map.put("systemStatus", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("dataField1", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("informationLayers", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("dataField2", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("parameter1", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("parameter2", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("parameter3", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("parameter4", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("parameter5", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("parameter6", Short.toUnsignedInt(byteBuffer.getShort()));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    byteBuffer.put(((Number) map.get("systemStatus")).byteValue());
    byteBuffer.put(((Number) map.get("dataField1")).byteValue());
    byteBuffer.put(((Number) map.get("informationLayers")).byteValue());
    byteBuffer.put(((Number) map.get("dataField2")).byteValue());
    byteBuffer.putShort(((Number) map.get("parameter1")).shortValue());
    byteBuffer.putShort(((Number) map.get("parameter2")).shortValue());
    byteBuffer.putShort(((Number) map.get("parameter3")).shortValue());
    byteBuffer.putShort(((Number) map.get("parameter4")).shortValue());
    byteBuffer.putShort(((Number) map.get("parameter5")).shortValue());
    byteBuffer.putShort(((Number) map.get("parameter6")).shortValue());
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += 1;  // systemStatus
    marshalSize += 1;  // dataField1
    marshalSize += 1;  // informationLayers
    marshalSize += 1;  // dataField2
    marshalSize += 2;  // parameter1
    marshalSize += 2;  // parameter2
    marshalSize += 2;  // parameter3
    marshalSize += 2;  // parameter4
    marshalSize += 2;  // parameter5
    marshalSize += 2;  // parameter6

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

 /**
  * Compare all fields that contribute to the state, ignoring
  * transient and static fields, for <code>this</code> and the supplied object
  * @param obj the object to compare to
  * @return true if the objects are equal, false otherwise.
  */
 public synchronized boolean equalsImpl(Object obj)
 {
     final FundamentalOperationalData rhs = (FundamentalOperationalData)obj;

     if( ! (systemStatus == rhs.systemStatus)) return false;
     if( ! (dataField1 == rhs.dataField1)) return false;
     if( ! (informationLayers == rhs.informationLayers)) return false;
     if( ! (dataField2 == rhs.dataField2)) return false;
     if( ! (parameter1 == rhs.parameter1)) return false;
     if( ! (parameter2 == rhs.parameter2)) return false;
     if( ! (parameter3 == rhs.parameter3)) return false;
     if( ! (parameter4 == rhs.parameter4)) return false;
     if( ! (parameter5 == rhs.parameter5)) return false;
     if( ! (parameter6 == rhs.parameter6)) return false;
    return true;
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" systemStatus:").append(systemStatus); // writeOneToString
    sb.append(" dataField1:").append(dataField1); // writeOneToString
    sb.append(" informationLayers:").append(informationLayers); // writeOneToString
    sb.append(" dataField2:").append(dataField2); // writeOneToString
    sb.append(" parameter1:").append(parameter1); // writeOneToString
    sb.append(" parameter2:").append(parameter2); // writeOneToString
    sb.append(" parameter3:").append(parameter3); // writeOneToString
    sb.append(" parameter4:").append(parameter4); // writeOneToString
    sb.append(" parameter5:").append(parameter5); // writeOneToString
    sb.append(" parameter6:").append(parameter6); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.systemStatus,
	                     this.dataField1,
	                     this.informationLayers,
	                     this.dataField2,
	                     this.parameter1,
	                     this.parameter2,
	                     this.parameter3,
	                     this.parameter4,
	                     this.parameter5,
	                     this.parameter6);
 }
} // end of FundamentalOperationalData
