/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;
import java.nio.ByteBuffer;

/**
 * 7.10.3 Used to communicate information about global, spatially varying environmental effects.
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class GriddedDataPdu extends SyntheticEnvironmentFamilyPdu implements Serializable, Marshaller
{

   /** The name of this PDU type */
   public static final String NAME = "GriddedDataPdu";
   
   /** environmental simulation application ID provides a unique identifier */
   protected SimulationIdentifier  environmentalSimulationApplicationID = new SimulationIdentifier(); 

   /** unique identifier for each piece of environmental data 
   Value space: uint16 */
   protected int fieldNumber;

   /** sequence number for the total set of PDUS used to transmit the data 
   Value space: uint16 */
   protected int pduNumber;

   /** Total number of PDUS used to transmit the data 
   Value space: uint16 */
   protected int pduTotal;

   /** coordinate system of the grid uid 244 */
   protected GriddedDataCoordinateSystem coordinateSystem = GriddedDataCoordinateSystem.values()[0];

   /** number of grid axes for the environmental data 
   Value space: uint8 */
   protected int numberOfGridAxes;

   /** are domain grid axes identidal to those of the priveious domain update? uid 245 */
   protected GriddedDataConstantGrid constantGrid = GriddedDataConstantGrid.values()[0];

   /** type of environment */
   protected EntityType  environmentType = new EntityType(); 

   /** orientation of the data grid */
   protected EulerAngles  orientation = new EulerAngles(); 

   /** valid time of the enviormental data sample, 64-bit unsigned int */
   protected ClockTime  sampleTime = new ClockTime(); 

   /** total number of all data values for all pdus for an environmental sample 
   Value space: uint32 */
   protected UnsignedInteger totalValues = UnsignedInteger.ZERO;

   /** total number of data values at each grid point. 
   Value space: uint8 */
   protected int vectorDimension;

   /** padding 
   Value space: uint8 */
   protected int padding1;

   /** padding 
   Value space: uint16 */
   protected int padding2;

   /** gridAxisDescriptors is an undescribed parameter... */
   protected List< GridAxisDescriptor > gridAxisDescriptors = new ArrayList<>();
 
   /** gridDataRecords is an undescribed parameter... */
   protected List< GridData > gridDataRecords = new ArrayList<>();
 

/** Constructor creates and configures a new instance object */
 public GriddedDataPdu()
 {
    setPduType( DisPduType.GRIDDED_DATA );
 }
/** copy method creates a deep copy of current object using preferred marshalling method
 * @return deep copy of PDU */
 public synchronized GriddedDataPdu copy()
 {
     return copyDataOutputStream();
 }
/** Creates a "deep copy" of current object using ByteBuffer methods.
 * @return deep copy of PDU */
 public synchronized GriddedDataPdu copyByteBuffer()
 {
     GriddedDataPdu newCopy = new GriddedDataPdu();
     ByteBuffer byteBuffer = ByteBuffer.allocate(400);
     try
     {
         this.marshal(byteBuffer);      // working
         newCopy.unmarshal(byteBuffer); // not working
     }
     catch (Exception e)
     {
         System.err.println("GriddedDataPdu deep copy() marshall/unmarshall ByteBuffer exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
     return newCopy;
 }

/** byteArrayOutputStream (baos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
/** dataOutputStream (dos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected DataOutputStream      dataOutputStream      = new DataOutputStream(byteArrayOutputStream);

/** copy method creates a deep copy of current object using DataOutputStream methods.
 * @return deep copy of PDU */
 public synchronized GriddedDataPdu copyDataOutputStream()
 {
     GriddedDataPdu newCopy = new GriddedDataPdu();
     try
     {
         this.marshal(dataOutputStream);
         byte[] byteArrayDOS = byteArrayOutputStream.toByteArray();
         newCopy.unmarshal(ByteBuffer.wrap(byteArrayDOS));
     }
     catch (Exception e)
     {
         System.err.println("GriddedDataPdu deep copy() marshall/unmarshall DataOutputStream exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
        try
        {
                 dataOutputStream.flush();
            byteArrayOutputStream.flush();
            byteArrayOutputStream.reset();
        }
        catch (IOException ioe)
        {
            System.err.println("GriddedDataPdu copyDataOutputStream() flush IOException: " + ioe.getMessage());
        }
     return newCopy;
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   if (environmentalSimulationApplicationID != null)
       marshalSize += environmentalSimulationApplicationID.getMarshalledSize();
   marshalSize += 2;  // fieldNumber
   marshalSize += 2;  // pduNumber
   marshalSize += 2;  // pduTotal
   if (coordinateSystem != null)
       marshalSize += coordinateSystem.getMarshalledSize();
   marshalSize += 1;  // numberOfGridAxes
   if (constantGrid != null)
       marshalSize += constantGrid.getMarshalledSize();
   if (environmentType != null)
       marshalSize += environmentType.getMarshalledSize();
   if (orientation != null)
       marshalSize += orientation.getMarshalledSize();
   if (sampleTime != null)
       marshalSize += sampleTime.getMarshalledSize();
   marshalSize += 4;  // totalValues
   marshalSize += 1;  // vectorDimension
   marshalSize += 1;  // padding1
   marshalSize += 2;  // padding2
   if (gridAxisDescriptors != null)
       for (int idx=0; idx < gridAxisDescriptors.size(); idx++)
       {
            GridAxisDescriptor listElement = gridAxisDescriptors.get(idx);
            marshalSize += listElement.getMarshalledSize();
       }
   if (gridDataRecords != null)
       for (int idx=0; idx < gridDataRecords.size(); idx++)
       {
            GridData listElement = gridDataRecords.get(idx);
            marshalSize += listElement.getMarshalledSize();
       }

   return marshalSize;
}


/** Setter for {@link GriddedDataPdu#environmentalSimulationApplicationID}
  * @param pEnvironmentalSimulationApplicationID new value of interest
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setEnvironmentalSimulationApplicationID(SimulationIdentifier pEnvironmentalSimulationApplicationID)
{
    environmentalSimulationApplicationID = pEnvironmentalSimulationApplicationID;
    return this;
}
/** Getter for {@link GriddedDataPdu#environmentalSimulationApplicationID}
  * @return value of interest */
public SimulationIdentifier getEnvironmentalSimulationApplicationID()
{
    return environmentalSimulationApplicationID;
}


/** Setter for {@link GriddedDataPdu#fieldNumber}
  * @param pFieldNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setFieldNumber(int pFieldNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pFieldNumber >= 0 && pFieldNumber <= 65535, "Value outside valid value space");
    fieldNumber = pFieldNumber;
    return this;
}
/** Getter for {@link GriddedDataPdu#fieldNumber}
  * @return value of interest */
public int getFieldNumber()
{
    return fieldNumber; 
}

/** Setter for {@link GriddedDataPdu#pduNumber}
  * @param pPduNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setPduNumber(int pPduNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pPduNumber >= 0 && pPduNumber <= 65535, "Value outside valid value space");
    pduNumber = pPduNumber;
    return this;
}
/** Getter for {@link GriddedDataPdu#pduNumber}
  * @return value of interest */
public int getPduNumber()
{
    return pduNumber; 
}

/** Setter for {@link GriddedDataPdu#pduTotal}
  * @param pPduTotal new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setPduTotal(int pPduTotal)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pPduTotal >= 0 && pPduTotal <= 65535, "Value outside valid value space");
    pduTotal = pPduTotal;
    return this;
}
/** Getter for {@link GriddedDataPdu#pduTotal}
  * @return value of interest */
public int getPduTotal()
{
    return pduTotal; 
}

/** Setter for {@link GriddedDataPdu#coordinateSystem}
  * @param pCoordinateSystem new value of interest
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setCoordinateSystem(GriddedDataCoordinateSystem pCoordinateSystem)
{
    coordinateSystem = pCoordinateSystem;
    return this;
}
/** Getter for {@link GriddedDataPdu#coordinateSystem}
  * @return value of interest */
public GriddedDataCoordinateSystem getCoordinateSystem()
{
    return coordinateSystem; 
}

/** Setter for {@link GriddedDataPdu#constantGrid}
  * @param pConstantGrid new value of interest
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setConstantGrid(GriddedDataConstantGrid pConstantGrid)
{
    constantGrid = pConstantGrid;
    return this;
}
/** Getter for {@link GriddedDataPdu#constantGrid}
  * @return value of interest */
public GriddedDataConstantGrid getConstantGrid()
{
    return constantGrid; 
}

/** Setter for {@link GriddedDataPdu#environmentType}
  * @param pEnvironmentType new value of interest
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setEnvironmentType(EntityType pEnvironmentType)
{
    environmentType = pEnvironmentType;
    return this;
}
/** Getter for {@link GriddedDataPdu#environmentType}
  * @return value of interest */
public EntityType getEnvironmentType()
{
    return environmentType;
}


/** Setter for {@link GriddedDataPdu#orientation}
  * @param pOrientation new value of interest
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setOrientation(EulerAngles pOrientation)
{
    orientation = pOrientation;
    return this;
}
/** Getter for {@link GriddedDataPdu#orientation}
  * @return value of interest */
public EulerAngles getOrientation()
{
    return orientation;
}


/** Setter for {@link GriddedDataPdu#sampleTime}
  * @param pSampleTime new value of interest
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setSampleTime(ClockTime pSampleTime)
{
    sampleTime = pSampleTime;
    return this;
}
/** Getter for {@link GriddedDataPdu#sampleTime}
  * @return value of interest */
public ClockTime getSampleTime()
{
    return sampleTime;
}


/** Setter for {@link GriddedDataPdu#totalValues}
  * @param pTotalValues new value of interest. Value space uint32
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setTotalValues(UnsignedInteger pTotalValues)
{
    totalValues = pTotalValues;
    return this;
}
/** Getter for {@link GriddedDataPdu#totalValues}
  * @return value of interest */
public UnsignedInteger getTotalValues()
{
    return totalValues; 
}

/** Setter for {@link GriddedDataPdu#vectorDimension}
  * @param pVectorDimension new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setVectorDimension(int pVectorDimension)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pVectorDimension >= 0 && pVectorDimension <= 255, "Value outside valid value space");
    vectorDimension = pVectorDimension;
    return this;
}
/** Getter for {@link GriddedDataPdu#vectorDimension}
  * @return value of interest */
public int getVectorDimension()
{
    return vectorDimension; 
}

/** Setter for {@link GriddedDataPdu#padding1}
  * @param pPadding1 new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setPadding1(int pPadding1)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pPadding1 >= 0 && pPadding1 <= 255, "Value outside valid value space");
    padding1 = pPadding1;
    return this;
}
/** Getter for {@link GriddedDataPdu#padding1}
  * @return value of interest */
public int getPadding1()
{
    return padding1; 
}

/** Setter for {@link GriddedDataPdu#padding2}
  * @param pPadding2 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setPadding2(int pPadding2)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pPadding2 >= 0 && pPadding2 <= 65535, "Value outside valid value space");
    padding2 = pPadding2;
    return this;
}
/** Getter for {@link GriddedDataPdu#padding2}
  * @return value of interest */
public int getPadding2()
{
    return padding2; 
}

/** Setter for {@link GriddedDataPdu#gridAxisDescriptors}
  * @param pGridAxisDescriptors new value of interest
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setGridAxisDescriptors(List<GridAxisDescriptor> pGridAxisDescriptors)
{
    gridAxisDescriptors = pGridAxisDescriptors;
    return this;
}
/** Getter for {@link GriddedDataPdu#gridAxisDescriptors}
  * @return value of interest */
public List<GridAxisDescriptor> getGridAxisDescriptors()
{
    return gridAxisDescriptors; 
}

/** Setter for {@link GriddedDataPdu#gridDataRecords}
  * @param pGridDataRecords new value of interest
  * @return same object to permit progressive setters */
public synchronized GriddedDataPdu setGridDataRecords(List<GridData> pGridDataRecords)
{
    gridDataRecords = pGridDataRecords;
    return this;
}
/** Getter for {@link GriddedDataPdu#gridDataRecords}
  * @return value of interest */
public List<GridData> getGridDataRecords()
{
    return gridDataRecords; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    super.marshal(dos);

    {
       environmentalSimulationApplicationID.marshal(dos);
       dos.writeShort((short) fieldNumber);
       dos.writeShort((short) pduNumber);
       dos.writeShort((short) pduTotal);
       coordinateSystem.marshal(dos);
       dos.writeByte(gridDataRecords.size());
       constantGrid.marshal(dos);
       environmentType.marshal(dos);
       orientation.marshal(dos);
       sampleTime.marshal(dos);
       dos.writeInt(totalValues.intValue());
       dos.writeByte((byte) vectorDimension);
       dos.writeByte((byte) padding1);
       dos.writeShort((short) padding2);

       for (int idx = 0; idx < gridAxisDescriptors.size(); idx++)
       {
            GridAxisDescriptor aGridAxisDescriptor = gridAxisDescriptors.get(idx);
            aGridAxisDescriptor.marshal(dos);
       }


       for (int idx = 0; idx < gridDataRecords.size(); idx++)
       {
            GridData aGridData = gridDataRecords.get(idx);
            aGridData.marshal(dos);
       }

    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    uPosition += super.unmarshal(dis);


    {
        uPosition += environmentalSimulationApplicationID.unmarshal(dis);
        fieldNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        pduNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        pduTotal = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        coordinateSystem = GriddedDataCoordinateSystem.unmarshalEnum(dis);
        uPosition += coordinateSystem.getMarshalledSize();
        numberOfGridAxes = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        constantGrid = GriddedDataConstantGrid.unmarshalEnum(dis);
        uPosition += constantGrid.getMarshalledSize();
        uPosition += environmentType.unmarshal(dis);
        uPosition += orientation.unmarshal(dis);
        uPosition += sampleTime.unmarshal(dis);
        totalValues = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
        vectorDimension = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        padding1 = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        padding2 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        for (int idx = 0; idx < ((Number) numberOfGridAxes).intValue(); idx++)
        {
            GridAxisDescriptor anX = new GridAxisDescriptor();
            uPosition += anX.unmarshal(dis);
            gridAxisDescriptors.add(anX);
        }

        for (int idx = 0; idx < ((Number) numberOfGridAxes).intValue(); idx++)
        {
            GridData anX = new GridData();
            uPosition += anX.unmarshal(dis);
            gridDataRecords.add(anX);
        }

    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   super.marshal(byteBuffer);
   environmentalSimulationApplicationID.marshal(byteBuffer);
   byteBuffer.putShort((short) fieldNumber);
   byteBuffer.putShort((short) pduNumber);
   byteBuffer.putShort((short) pduTotal);
   coordinateSystem.marshal(byteBuffer);
   byteBuffer.put( (byte)gridDataRecords.size());
   constantGrid.marshal(byteBuffer);
   environmentType.marshal(byteBuffer);
   orientation.marshal(byteBuffer);
   sampleTime.marshal(byteBuffer);
   byteBuffer.putInt(totalValues.intValue());
   byteBuffer.put((byte) vectorDimension);
   byteBuffer.put((byte) padding1);
   byteBuffer.putShort((short) padding2);

   for (int idx = 0; idx < gridAxisDescriptors.size(); idx++)
   {
        GridAxisDescriptor aGridAxisDescriptor = gridAxisDescriptors.get(idx);
        aGridAxisDescriptor.marshal(byteBuffer);
   }


   for (int idx = 0; idx < gridDataRecords.size(); idx++)
   {
        GridData aGridData = gridDataRecords.get(idx);
        aGridData.marshal(byteBuffer);
   }

}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    super.unmarshal(byteBuffer);

    {
        environmentalSimulationApplicationID.unmarshal(byteBuffer);
        fieldNumber = Short.toUnsignedInt(byteBuffer.getShort());
        pduNumber = Short.toUnsignedInt(byteBuffer.getShort());
        pduTotal = Short.toUnsignedInt(byteBuffer.getShort());
        coordinateSystem = GriddedDataCoordinateSystem.unmarshalEnum(byteBuffer);
        numberOfGridAxes = Byte.toUnsignedInt(byteBuffer.get());
        constantGrid = GriddedDataConstantGrid.unmarshalEnum(byteBuffer);
        environmentType.unmarshal(byteBuffer);
        orientation.unmarshal(byteBuffer);
        sampleTime.unmarshal(byteBuffer);
        totalValues = UnsignedInteger.fromIntBits(byteBuffer.getInt());
        vectorDimension = Byte.toUnsignedInt(byteBuffer.get());
        padding1 = Byte.toUnsignedInt(byteBuffer.get());
        padding2 = Short.toUnsignedInt(byteBuffer.getShort());
        for (int idx = 0; idx < ((Number) numberOfGridAxes).intValue(); idx++)
        {
            GridAxisDescriptor anX = new GridAxisDescriptor();
            anX.unmarshal(byteBuffer);
            gridAxisDescriptors.add(anX);
        }

        for (int idx = 0; idx < ((Number) numberOfGridAxes).intValue(); idx++)
        {
            GridData anX = new GridData();
            anX.unmarshal(byteBuffer);
            gridDataRecords.add(anX);
        }

    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = SyntheticEnvironmentFamilyPdu.fromBufferToMap(byteBuffer);

    map.put("environmentalSimulationApplicationID", SimulationIdentifier.fromBufferToMap(byteBuffer));
    map.put("fieldNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("pduNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("pduTotal", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("coordinateSystem", GriddedDataCoordinateSystem.unmarshalEnum(byteBuffer).getValue());
    map.put("numberOfGridAxes", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("constantGrid", GriddedDataConstantGrid.unmarshalEnum(byteBuffer).getValue());
    map.put("environmentType", EntityType.fromBufferToMap(byteBuffer));
    map.put("orientation", EulerAngles.fromBufferToMap(byteBuffer));
    map.put("sampleTime", ClockTime.fromBufferToMap(byteBuffer));
    map.put("totalValues", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    map.put("vectorDimension", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("padding1", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("padding2", Short.toUnsignedInt(byteBuffer.getShort()));
    List gridAxisDescriptors = new ArrayList<>();
    for (int idx = 0; idx < ((Number) map.get("numberOfGridAxes")).intValue(); idx++)
    {
        gridAxisDescriptors.add(GridAxisDescriptor.fromBufferToMap(byteBuffer));
    }
    map.put("gridAxisDescriptors", gridAxisDescriptors);

    List gridDataRecords = new ArrayList<>();
    for (int idx = 0; idx < ((Number) map.get("numberOfGridAxes")).intValue(); idx++)
    {
        gridDataRecords.add(GridData.fromBufferToMap(byteBuffer));
    }
    map.put("gridDataRecords", gridDataRecords);

    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    SyntheticEnvironmentFamilyPdu.fromMapToBuffer(map, byteBuffer);
    SimulationIdentifier.fromMapToBuffer((PduMap) map.get("environmentalSimulationApplicationID"), byteBuffer);
    byteBuffer.putShort(((Number) map.get("fieldNumber")).shortValue());
    byteBuffer.putShort(((Number) map.get("pduNumber")).shortValue());
    byteBuffer.putShort(((Number) map.get("pduTotal")).shortValue());
    GriddedDataCoordinateSystem.getEnumForValue(((Number) map.get("coordinateSystem")).intValue()).marshal(byteBuffer);
    byteBuffer.put(((Number) map.get("numberOfGridAxes")).byteValue());
    GriddedDataConstantGrid.getEnumForValue(((Number) map.get("constantGrid")).intValue()).marshal(byteBuffer);
    EntityType.fromMapToBuffer((PduMap) map.get("environmentType"), byteBuffer);
    EulerAngles.fromMapToBuffer((PduMap) map.get("orientation"), byteBuffer);
    ClockTime.fromMapToBuffer((PduMap) map.get("sampleTime"), byteBuffer);
    byteBuffer.putInt(((Number) map.get("totalValues")).intValue());
    byteBuffer.put(((Number) map.get("vectorDimension")).byteValue());
    byteBuffer.put(((Number) map.get("padding1")).byteValue());
    byteBuffer.putShort(((Number) map.get("padding2")).shortValue());

    List gridAxisDescriptors = (List) map.get("gridAxisDescriptors");
    for (int idx = 0; idx < ((Number) map.get("numberOfGridAxes")).intValue(); idx++)
    {
        GridAxisDescriptor.fromMapToBuffer((PduMap) gridAxisDescriptors.get(idx), byteBuffer);
    }


    List gridDataRecords = (List) map.get("gridDataRecords");
    for (int idx = 0; idx < ((Number) map.get("numberOfGridAxes")).intValue(); idx++)
    {
        GridData.fromMapToBuffer((PduMap) gridDataRecords.get(idx), byteBuffer);
    }

}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += SyntheticEnvironmentFamilyPdu.getMarshalledSize(map);
    marshalSize += SimulationIdentifier.getMarshalledSize((PduMap) map.get("environmentalSimulationApplicationID"));
    marshalSize += 2;  // fieldNumber
    marshalSize += 2;  // pduNumber
    marshalSize += 2;  // pduTotal
    marshalSize += GriddedDataCoordinateSystem.getEnumForValue(((Number) map.get("coordinateSystem")).intValue()).getMarshalledSize();
    marshalSize += 1;  // numberOfGridAxes
    marshalSize += GriddedDataConstantGrid.getEnumForValue(((Number) map.get("constantGrid")).intValue()).getMarshalledSize();
    marshalSize += EntityType.getMarshalledSize((PduMap) map.get("environmentType"));
    marshalSize += EulerAngles.getMarshalledSize((PduMap) map.get("orientation"));
    marshalSize += ClockTime.getMarshalledSize((PduMap) map.get("sampleTime"));
    marshalSize += 4;  // totalValues
    marshalSize += 1;  // vectorDimension
    marshalSize += 1;  // padding1
    marshalSize += 2;  // padding2
    List gridAxisDescriptors = (List) map.get("gridAxisDescriptors");
    for (int idx = 0; idx < ((Number) map.get("numberOfGridAxes")).intValue(); idx++)
        marshalSize += GridAxisDescriptor.getMarshalledSize((PduMap) gridAxisDescriptors.get(idx));
    List gridDataRecords = (List) map.get("gridDataRecords");
    for (int idx = 0; idx < ((Number) map.get("numberOfGridAxes")).intValue(); idx++)
        marshalSize += GridData.getMarshalledSize((PduMap) gridDataRecords.get(idx));

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public synchronized boolean equalsImpl(Object obj)
 {
     final GriddedDataPdu rhs = (GriddedDataPdu)obj;

     if( ! Objects.equals(environmentalSimulationApplicationID, rhs.environmentalSimulationApplicationID) ) return false;
     if( ! (fieldNumber == rhs.fieldNumber)) return false;
     if( ! (pduNumber == rhs.pduNumber)) return false;
     if( ! (pduTotal == rhs.pduTotal)) return false;
     if( ! (coordinateSystem == rhs.coordinateSystem)) return false;
     if( ! (constantGrid == rhs.constantGrid)) return false;
     if( ! Objects.equals(environmentType, rhs.environmentType) ) return false;
     if( ! Objects.equals(orientation, rhs.orientation) ) return false;
     if( ! Objects.equals(sampleTime, rhs.sampleTime) ) return false;
     if( ! Objects.equals(totalValues, rhs.totalValues) ) return false;
     if( ! (vectorDimension == rhs.vectorDimension)) return false;
     if( ! (padding1 == rhs.padding1)) return false;
     if( ! (padding2 == rhs.padding2)) return false;
     if( ! Objects.equals(gridAxisDescriptors, rhs.gridAxisDescriptors) ) return false;
     if( ! Objects.equals(gridDataRecords, rhs.gridDataRecords) ) return false;
    return super.equalsImpl(rhs);
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(super.toString());
    sb.append(" environmentalSimulationApplicationID:").append(environmentalSimulationApplicationID); // writeOneToString
    sb.append(" fieldNumber:").append(fieldNumber); // writeOneToString
    sb.append(" pduNumber:").append(pduNumber); // writeOneToString
    sb.append(" pduTotal:").append(pduTotal); // writeOneToString
    sb.append(" coordinateSystem:").append(coordinateSystem); // writeOneToString
    sb.append(" constantGrid:").append(constantGrid); // writeOneToString
    sb.append(" environmentType:").append(environmentType); // writeOneToString
    sb.append(" orientation:").append(orientation); // writeOneToString
    sb.append(" sampleTime:").append(sampleTime); // writeOneToString
    sb.append(" totalValues:").append(totalValues); // writeOneToString
    sb.append(" vectorDimension:").append(vectorDimension); // writeOneToString
    sb.append(" padding1:").append(padding1); // writeOneToString
    sb.append(" padding2:").append(padding2); // writeOneToString
    sb.append(" gridAxisDescriptors: ");
    gridAxisDescriptors.forEach(r->{ sb2.append(" ").append(r);}); // writeList
    sb.append(sb2.toString().trim());
    // https://stackoverflow.com/questions/2242471/clearing-a-string-buffer-builder-after-loop
    sb2.setLength(0); // reset
    sb.append(" gridDataRecords: ");
    gridDataRecords.forEach(r->{ sb2.append(" ").append(r);}); // writeList
    sb.append(sb2.toString().trim());
    // https://stackoverflow.com/questions/2242471/clearing-a-string-buffer-builder-after-loop
    sb2.setLength(0); // reset

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.environmentalSimulationApplicationID,
	                     this.fieldNumber,
	                     this.pduNumber,
	                     this.pduTotal,
	                     this.coordinateSystem,
	                     this.numberOfGridAxes,
	                     this.constantGrid,
	                     this.environmentType,
	                     this.orientation,
	                     this.sampleTime,
	                     this.totalValues,
	                     this.vectorDimension,
	                     this.padding1,
	                     this.padding2,
	                     this.gridAxisDescriptors,
	                     this.gridDataRecords);
 }
} // end of GriddedDataPdu
