/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;

/**
 * 7.6.5.6. Layer 5 data communications
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class IFFPduLayer5Data extends AbstractIFFPduLayerData implements Serializable, Marshaller
{
   /** Layer header */
   protected LayerHeader  layerHeader = new LayerHeader(); 

   /** 6.2.80 Site number, part of reporting simulation field 
   Value space: uint16 */
   protected int siteNumber;

   /** 6.2.80 Application number, part of reporting simulation field 
   Value space: uint16 */
   protected int applicationNumber;

   /** Padding 
   Value space: uint16 */
   protected int padding;

   /** Eight boolean fields. See 6.2.45. 
   Value space: uint8 */
   protected int applicableLayers;

   /** Data category uid 369 */
   protected DataCategory dataCategory = DataCategory.values()[0];

   /** Padding 
   Value space: uint16 */
   protected int padding2;

   /** Variable length list of fundamental parameters. */
   protected IFFDataSpecification  IFFFundamentalParameterDataRecord = new IFFDataSpecification(); 


/** Constructor creates and configures a new instance object */
 public IFFPduLayer5Data()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   if (layerHeader != null)
       marshalSize += layerHeader.getMarshalledSize();
   marshalSize += 2;  // siteNumber
   marshalSize += 2;  // applicationNumber
   marshalSize += 2;  // padding
   marshalSize += 1;  // applicableLayers
   if (dataCategory != null)
       marshalSize += dataCategory.getMarshalledSize();
   marshalSize += 2;  // padding2
   if (IFFFundamentalParameterDataRecord != null)
       marshalSize += IFFFundamentalParameterDataRecord.getMarshalledSize();

   return marshalSize;
}


/** Setter for {@link IFFPduLayer5Data#layerHeader}
  * @param pLayerHeader new value of interest
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer5Data setLayerHeader(LayerHeader pLayerHeader)
{
    layerHeader = pLayerHeader;
    return this;
}
/** Getter for {@link IFFPduLayer5Data#layerHeader}
  * @return value of interest */
public LayerHeader getLayerHeader()
{
    return layerHeader;
}


/** Setter for {@link IFFPduLayer5Data#siteNumber}
  * @param pSiteNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer5Data setSiteNumber(int pSiteNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pSiteNumber >= 0 && pSiteNumber <= 65535, "Value outside valid value space");
    siteNumber = pSiteNumber;
    return this;
}
/** Getter for {@link IFFPduLayer5Data#siteNumber}
  * @return value of interest */
public int getSiteNumber()
{
    return siteNumber; 
}

/** Setter for {@link IFFPduLayer5Data#applicationNumber}
  * @param pApplicationNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer5Data setApplicationNumber(int pApplicationNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pApplicationNumber >= 0 && pApplicationNumber <= 65535, "Value outside valid value space");
    applicationNumber = pApplicationNumber;
    return this;
}
/** Getter for {@link IFFPduLayer5Data#applicationNumber}
  * @return value of interest */
public int getApplicationNumber()
{
    return applicationNumber; 
}

/** Setter for {@link IFFPduLayer5Data#padding}
  * @param pPadding new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer5Data setPadding(int pPadding)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pPadding >= 0 && pPadding <= 65535, "Value outside valid value space");
    padding = pPadding;
    return this;
}
/** Getter for {@link IFFPduLayer5Data#padding}
  * @return value of interest */
public int getPadding()
{
    return padding; 
}

/** Setter for {@link IFFPduLayer5Data#applicableLayers}
  * @param pApplicableLayers new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer5Data setApplicableLayers(int pApplicableLayers)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pApplicableLayers >= 0 && pApplicableLayers <= 255, "Value outside valid value space");
    applicableLayers = pApplicableLayers;
    return this;
}
/** Getter for {@link IFFPduLayer5Data#applicableLayers}
  * @return value of interest */
public int getApplicableLayers()
{
    return applicableLayers; 
}

/** Setter for {@link IFFPduLayer5Data#dataCategory}
  * @param pDataCategory new value of interest
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer5Data setDataCategory(DataCategory pDataCategory)
{
    dataCategory = pDataCategory;
    return this;
}
/** Getter for {@link IFFPduLayer5Data#dataCategory}
  * @return value of interest */
public DataCategory getDataCategory()
{
    return dataCategory; 
}

/** Setter for {@link IFFPduLayer5Data#padding2}
  * @param pPadding2 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer5Data setPadding2(int pPadding2)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pPadding2 >= 0 && pPadding2 <= 65535, "Value outside valid value space");
    padding2 = pPadding2;
    return this;
}
/** Getter for {@link IFFPduLayer5Data#padding2}
  * @return value of interest */
public int getPadding2()
{
    return padding2; 
}

/** Setter for {@link IFFPduLayer5Data#IFFFundamentalParameterDataRecord}
  * @param pIFFFundamentalParameterDataRecord new value of interest
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer5Data setIFFFundamentalParameterDataRecord(IFFDataSpecification pIFFFundamentalParameterDataRecord)
{
    IFFFundamentalParameterDataRecord = pIFFFundamentalParameterDataRecord;
    return this;
}
/** Getter for {@link IFFPduLayer5Data#IFFFundamentalParameterDataRecord}
  * @return value of interest */
public IFFDataSpecification getIFFFundamentalParameterDataRecord()
{
    return IFFFundamentalParameterDataRecord;
}


/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    super.marshal(dos);

    {
       layerHeader.marshal(dos);
       dos.writeShort((short) siteNumber);
       dos.writeShort((short) applicationNumber);
       dos.writeShort((short) padding);
       dos.writeByte((byte) applicableLayers);
       dataCategory.marshal(dos);
       dos.writeShort((short) padding2);
       IFFFundamentalParameterDataRecord.marshal(dos);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    uPosition += super.unmarshal(dis);


    {
        uPosition += layerHeader.unmarshal(dis);
        siteNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        applicationNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        padding = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        applicableLayers = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        dataCategory = DataCategory.unmarshalEnum(dis);
        uPosition += dataCategory.getMarshalledSize();
        padding2 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        uPosition += IFFFundamentalParameterDataRecord.unmarshal(dis);
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   super.marshal(byteBuffer);
   layerHeader.marshal(byteBuffer);
   byteBuffer.putShort((short) siteNumber);
   byteBuffer.putShort((short) applicationNumber);
   byteBuffer.putShort((short) padding);
   byteBuffer.put((byte) applicableLayers);
   dataCategory.marshal(byteBuffer);
   byteBuffer.putShort((short) padding2);
   IFFFundamentalParameterDataRecord.marshal(byteBuffer);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    super.unmarshal(byteBuffer);

    {
        layerHeader.unmarshal(byteBuffer);
        siteNumber = Short.toUnsignedInt(byteBuffer.getShort());
        applicationNumber = Short.toUnsignedInt(byteBuffer.getShort());
        padding = Short.toUnsignedInt(byteBuffer.getShort());
        applicableLayers = Byte.toUnsignedInt(byteBuffer.get());
        dataCategory = DataCategory.unmarshalEnum(byteBuffer);
        padding2 = Short.toUnsignedInt(byteBuffer.getShort());
        IFFFundamentalParameterDataRecord.unmarshal(byteBuffer);
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = AbstractIFFPduLayerData.fromBufferToMap(byteBuffer);

    map.put("layerHeader", LayerHeader.fromBufferToMap(byteBuffer));
    map.put("siteNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("applicationNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("padding", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("applicableLayers", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("dataCategory", DataCategory.unmarshalEnum(byteBuffer).getValue());
    map.put("padding2", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("IFFFundamentalParameterDataRecord", IFFDataSpecification.fromBufferToMap(byteBuffer));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    AbstractIFFPduLayerData.fromMapToBuffer(map, byteBuffer);
    LayerHeader.fromMapToBuffer((PduMap) map.get("layerHeader"), byteBuffer);
    byteBuffer.putShort(((Number) map.get("siteNumber")).shortValue());
    byteBuffer.putShort(((Number) map.get("applicationNumber")).shortValue());
    byteBuffer.putShort(((Number) map.get("padding")).shortValue());
    byteBuffer.put(((Number) map.get("applicableLayers")).byteValue());
    DataCategory.getEnumForValue(((Number) map.get("dataCategory")).intValue()).marshal(byteBuffer);
    byteBuffer.putShort(((Number) map.get("padding2")).shortValue());
    IFFDataSpecification.fromMapToBuffer((PduMap) map.get("IFFFundamentalParameterDataRecord"), byteBuffer);
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += AbstractIFFPduLayerData.getMarshalledSize(map);
    marshalSize += LayerHeader.getMarshalledSize((PduMap) map.get("layerHeader"));
    marshalSize += 2;  // siteNumber
    marshalSize += 2;  // applicationNumber
    marshalSize += 2;  // padding
    marshalSize += 1;  // applicableLayers
    marshalSize += DataCategory.getEnumForValue(((Number) map.get("dataCategory")).intValue()).getMarshalledSize();
    marshalSize += 2;  // padding2
    marshalSize += IFFDataSpecification.getMarshalledSize((PduMap) map.get("IFFFundamentalParameterDataRecord"));

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public synchronized boolean equalsImpl(Object obj)
 {
     final IFFPduLayer5Data rhs = (IFFPduLayer5Data)obj;

     if( ! Objects.equals(layerHeader, rhs.layerHeader) ) return false;
     if( ! (siteNumber == rhs.siteNumber)) return false;
     if( ! (applicationNumber == rhs.applicationNumber)) return false;
     if( ! (padding == rhs.padding)) return false;
     if( ! (applicableLayers == rhs.applicableLayers)) return false;
     if( ! (dataCategory == rhs.dataCategory)) return false;
     if( ! (padding2 == rhs.padding2)) return false;
     if( ! Objects.equals(IFFFundamentalParameterDataRecord, rhs.IFFFundamentalParameterDataRecord) ) return false;
    return super.equalsImpl(rhs);
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(super.toString());
    sb.append(" layerHeader:").append(layerHeader); // writeOneToString
    sb.append(" siteNumber:").append(siteNumber); // writeOneToString
    sb.append(" applicationNumber:").append(applicationNumber); // writeOneToString
    sb.append(" padding:").append(padding); // writeOneToString
    sb.append(" applicableLayers:").append(applicableLayers); // writeOneToString
    sb.append(" dataCategory:").append(dataCategory); // writeOneToString
    sb.append(" padding2:").append(padding2); // writeOneToString
    sb.append(" IFFFundamentalParameterDataRecord:").append(IFFFundamentalParameterDataRecord); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.layerHeader,
	                     this.siteNumber,
	                     this.applicationNumber,
	                     this.padding,
	                     this.applicableLayers,
	                     this.dataCategory,
	                     this.padding2,
	                     this.IFFFundamentalParameterDataRecord);
 }
} // end of IFFPduLayer5Data
