/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;

/**
 * 7.6.5.4.3 Layer 3 Mode 5 transponder format
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class IFFPduLayer3TransponderFormatData extends AbstractIFFPduLayerData implements Serializable, Marshaller
{
   /** Layer header */
   protected LayerHeader  layerHeader = new LayerHeader(); 

   /** 6.2.80 Site number, part of reporting simulation field 
   Value space: uint16 */
   protected int siteNumber;

   /** 6.2.80 Application number, part of reporting simulation field 
   Value space: uint16 */
   protected int applicationNumber;

   /** Mode 5 transponder basic data */
   protected Mode5TransponderBasicData  mode5TransponderBasicData = new Mode5TransponderBasicData(); 

   /** Padding 
   Value space: uint16 */
   protected int padding;

   /** Variable length list of fundamental parameters. */
   protected IFFDataSpecification  IFFFundamentalParameterDataRecord = new IFFDataSpecification(); 


/** Constructor creates and configures a new instance object */
 public IFFPduLayer3TransponderFormatData()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   if (layerHeader != null)
       marshalSize += layerHeader.getMarshalledSize();
   marshalSize += 2;  // siteNumber
   marshalSize += 2;  // applicationNumber
   if (mode5TransponderBasicData != null)
       marshalSize += mode5TransponderBasicData.getMarshalledSize();
   marshalSize += 2;  // padding
   if (IFFFundamentalParameterDataRecord != null)
       marshalSize += IFFFundamentalParameterDataRecord.getMarshalledSize();

   return marshalSize;
}


/** Setter for {@link IFFPduLayer3TransponderFormatData#layerHeader}
  * @param pLayerHeader new value of interest
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer3TransponderFormatData setLayerHeader(LayerHeader pLayerHeader)
{
    layerHeader = pLayerHeader;
    return this;
}
/** Getter for {@link IFFPduLayer3TransponderFormatData#layerHeader}
  * @return value of interest */
public LayerHeader getLayerHeader()
{
    return layerHeader;
}


/** Setter for {@link IFFPduLayer3TransponderFormatData#siteNumber}
  * @param pSiteNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer3TransponderFormatData setSiteNumber(int pSiteNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pSiteNumber >= 0 && pSiteNumber <= 65535, "Value outside valid value space");
    siteNumber = pSiteNumber;
    return this;
}
/** Getter for {@link IFFPduLayer3TransponderFormatData#siteNumber}
  * @return value of interest */
public int getSiteNumber()
{
    return siteNumber; 
}

/** Setter for {@link IFFPduLayer3TransponderFormatData#applicationNumber}
  * @param pApplicationNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer3TransponderFormatData setApplicationNumber(int pApplicationNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pApplicationNumber >= 0 && pApplicationNumber <= 65535, "Value outside valid value space");
    applicationNumber = pApplicationNumber;
    return this;
}
/** Getter for {@link IFFPduLayer3TransponderFormatData#applicationNumber}
  * @return value of interest */
public int getApplicationNumber()
{
    return applicationNumber; 
}

/** Setter for {@link IFFPduLayer3TransponderFormatData#mode5TransponderBasicData}
  * @param pMode5TransponderBasicData new value of interest
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer3TransponderFormatData setMode5TransponderBasicData(Mode5TransponderBasicData pMode5TransponderBasicData)
{
    mode5TransponderBasicData = pMode5TransponderBasicData;
    return this;
}
/** Getter for {@link IFFPduLayer3TransponderFormatData#mode5TransponderBasicData}
  * @return value of interest */
public Mode5TransponderBasicData getMode5TransponderBasicData()
{
    return mode5TransponderBasicData;
}


/** Setter for {@link IFFPduLayer3TransponderFormatData#padding}
  * @param pPadding new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer3TransponderFormatData setPadding(int pPadding)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pPadding >= 0 && pPadding <= 65535, "Value outside valid value space");
    padding = pPadding;
    return this;
}
/** Getter for {@link IFFPduLayer3TransponderFormatData#padding}
  * @return value of interest */
public int getPadding()
{
    return padding; 
}

/** Setter for {@link IFFPduLayer3TransponderFormatData#IFFFundamentalParameterDataRecord}
  * @param pIFFFundamentalParameterDataRecord new value of interest
  * @return same object to permit progressive setters */
public synchronized IFFPduLayer3TransponderFormatData setIFFFundamentalParameterDataRecord(IFFDataSpecification pIFFFundamentalParameterDataRecord)
{
    IFFFundamentalParameterDataRecord = pIFFFundamentalParameterDataRecord;
    return this;
}
/** Getter for {@link IFFPduLayer3TransponderFormatData#IFFFundamentalParameterDataRecord}
  * @return value of interest */
public IFFDataSpecification getIFFFundamentalParameterDataRecord()
{
    return IFFFundamentalParameterDataRecord;
}


/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    super.marshal(dos);

    {
       layerHeader.marshal(dos);
       dos.writeShort((short) siteNumber);
       dos.writeShort((short) applicationNumber);
       mode5TransponderBasicData.marshal(dos);
       dos.writeShort((short) padding);
       IFFFundamentalParameterDataRecord.marshal(dos);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    uPosition += super.unmarshal(dis);


    {
        uPosition += layerHeader.unmarshal(dis);
        siteNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        applicationNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        uPosition += mode5TransponderBasicData.unmarshal(dis);
        padding = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        uPosition += IFFFundamentalParameterDataRecord.unmarshal(dis);
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   super.marshal(byteBuffer);
   layerHeader.marshal(byteBuffer);
   byteBuffer.putShort((short) siteNumber);
   byteBuffer.putShort((short) applicationNumber);
   mode5TransponderBasicData.marshal(byteBuffer);
   byteBuffer.putShort((short) padding);
   IFFFundamentalParameterDataRecord.marshal(byteBuffer);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    super.unmarshal(byteBuffer);

    {
        layerHeader.unmarshal(byteBuffer);
        siteNumber = Short.toUnsignedInt(byteBuffer.getShort());
        applicationNumber = Short.toUnsignedInt(byteBuffer.getShort());
        mode5TransponderBasicData.unmarshal(byteBuffer);
        padding = Short.toUnsignedInt(byteBuffer.getShort());
        IFFFundamentalParameterDataRecord.unmarshal(byteBuffer);
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = AbstractIFFPduLayerData.fromBufferToMap(byteBuffer);

    map.put("layerHeader", LayerHeader.fromBufferToMap(byteBuffer));
    map.put("siteNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("applicationNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("mode5TransponderBasicData", Mode5TransponderBasicData.fromBufferToMap(byteBuffer));
    map.put("padding", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("IFFFundamentalParameterDataRecord", IFFDataSpecification.fromBufferToMap(byteBuffer));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    AbstractIFFPduLayerData.fromMapToBuffer(map, byteBuffer);
    LayerHeader.fromMapToBuffer((PduMap) map.get("layerHeader"), byteBuffer);
    byteBuffer.putShort(((Number) map.get("siteNumber")).shortValue());
    byteBuffer.putShort(((Number) map.get("applicationNumber")).shortValue());
    Mode5TransponderBasicData.fromMapToBuffer((PduMap) map.get("mode5TransponderBasicData"), byteBuffer);
    byteBuffer.putShort(((Number) map.get("padding")).shortValue());
    IFFDataSpecification.fromMapToBuffer((PduMap) map.get("IFFFundamentalParameterDataRecord"), byteBuffer);
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += AbstractIFFPduLayerData.getMarshalledSize(map);
    marshalSize += LayerHeader.getMarshalledSize((PduMap) map.get("layerHeader"));
    marshalSize += 2;  // siteNumber
    marshalSize += 2;  // applicationNumber
    marshalSize += Mode5TransponderBasicData.getMarshalledSize((PduMap) map.get("mode5TransponderBasicData"));
    marshalSize += 2;  // padding
    marshalSize += IFFDataSpecification.getMarshalledSize((PduMap) map.get("IFFFundamentalParameterDataRecord"));

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public synchronized boolean equalsImpl(Object obj)
 {
     final IFFPduLayer3TransponderFormatData rhs = (IFFPduLayer3TransponderFormatData)obj;

     if( ! Objects.equals(layerHeader, rhs.layerHeader) ) return false;
     if( ! (siteNumber == rhs.siteNumber)) return false;
     if( ! (applicationNumber == rhs.applicationNumber)) return false;
     if( ! Objects.equals(mode5TransponderBasicData, rhs.mode5TransponderBasicData) ) return false;
     if( ! (padding == rhs.padding)) return false;
     if( ! Objects.equals(IFFFundamentalParameterDataRecord, rhs.IFFFundamentalParameterDataRecord) ) return false;
    return super.equalsImpl(rhs);
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(super.toString());
    sb.append(" layerHeader:").append(layerHeader); // writeOneToString
    sb.append(" siteNumber:").append(siteNumber); // writeOneToString
    sb.append(" applicationNumber:").append(applicationNumber); // writeOneToString
    sb.append(" mode5TransponderBasicData:").append(mode5TransponderBasicData); // writeOneToString
    sb.append(" padding:").append(padding); // writeOneToString
    sb.append(" IFFFundamentalParameterDataRecord:").append(IFFFundamentalParameterDataRecord); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.layerHeader,
	                     this.siteNumber,
	                     this.applicationNumber,
	                     this.mode5TransponderBasicData,
	                     this.padding,
	                     this.IFFFundamentalParameterDataRecord);
 }
} // end of IFFPduLayer3TransponderFormatData
