/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;
import java.nio.ByteBuffer;

/**
 * 5.8.7 Communicates the state of a particular intercom device, request an action of another intercom device, or respond to an action request.
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class IntercomControlPdu extends RadioCommunicationsFamilyPdu implements Serializable, Marshaller
{

   /** The name of this PDU type */
   public static final String NAME = "IntercomControlPdu";
   
   /** control type uid 180 */
   protected IntercomControlControlType controlType = IntercomControlControlType.values()[0];

   /** control type 
   Value space: uint8 */
   protected int communicationsChannelType;

   /** Source entity ID, this can also be ObjectIdentifier or UnattachedIdentifier */
   protected EntityID  sourceEntityID = new EntityID(); 

   /** The specific intercom device being simulated within an entity. 
   Value space: uint16 */
   protected int sourceIntercomNumber;

   /** Line number to which the intercom control refers 
   Value space: uint8 */
   protected int sourceLineID;

   /** priority of this message relative to transmissons from other intercom devices 
   Value space: uint8 */
   protected int transmitPriority;

   /** current transmit state of the line uid 183 */
   protected IntercomControlTransmitLineState transmitLineState = IntercomControlTransmitLineState.values()[0];

   /** detailed type requested. uid 182 */
   protected IntercomControlCommand command = IntercomControlCommand.values()[0];

   /** eid of the entity that has created this intercom channel, same comments as sourceEntityId */
   protected EntityID  masterIntercomReferenceID = new EntityID(); 

   /** specific intercom device that has created this intercom channel 
   Value space: uint16 */
   protected int masterIntercomNumber;

   /** masterChannelID is an undescribed parameter...
   Value space: uint16 */
   protected int masterChannelID;

   /** number of intercom parameters 
   Value space: uint32 */
   protected UnsignedInteger intercomParametersLength = UnsignedInteger.ZERO;

   /** intercomParameters is an undescribed parameter... */
   protected IntercomCommunicationsParameters  intercomParameters = new IntercomCommunicationsParameters(); 


/** Constructor creates and configures a new instance object */
 public IntercomControlPdu()
 {
    setPduType( DisPduType.INTERCOM_CONTROL );
 }
/** copy method creates a deep copy of current object using preferred marshalling method
 * @return deep copy of PDU */
 public synchronized IntercomControlPdu copy()
 {
     return copyDataOutputStream();
 }
/** Creates a "deep copy" of current object using ByteBuffer methods.
 * @return deep copy of PDU */
 public synchronized IntercomControlPdu copyByteBuffer()
 {
     IntercomControlPdu newCopy = new IntercomControlPdu();
     ByteBuffer byteBuffer = ByteBuffer.allocate(400);
     try
     {
         this.marshal(byteBuffer);      // working
         newCopy.unmarshal(byteBuffer); // not working
     }
     catch (Exception e)
     {
         System.err.println("IntercomControlPdu deep copy() marshall/unmarshall ByteBuffer exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
     return newCopy;
 }

/** byteArrayOutputStream (baos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
/** dataOutputStream (dos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected DataOutputStream      dataOutputStream      = new DataOutputStream(byteArrayOutputStream);

/** copy method creates a deep copy of current object using DataOutputStream methods.
 * @return deep copy of PDU */
 public synchronized IntercomControlPdu copyDataOutputStream()
 {
     IntercomControlPdu newCopy = new IntercomControlPdu();
     try
     {
         this.marshal(dataOutputStream);
         byte[] byteArrayDOS = byteArrayOutputStream.toByteArray();
         newCopy.unmarshal(ByteBuffer.wrap(byteArrayDOS));
     }
     catch (Exception e)
     {
         System.err.println("IntercomControlPdu deep copy() marshall/unmarshall DataOutputStream exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
        try
        {
                 dataOutputStream.flush();
            byteArrayOutputStream.flush();
            byteArrayOutputStream.reset();
        }
        catch (IOException ioe)
        {
            System.err.println("IntercomControlPdu copyDataOutputStream() flush IOException: " + ioe.getMessage());
        }
     return newCopy;
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   if (controlType != null)
       marshalSize += controlType.getMarshalledSize();
   marshalSize += 1;  // communicationsChannelType
   if (sourceEntityID != null)
       marshalSize += sourceEntityID.getMarshalledSize();
   marshalSize += 2;  // sourceIntercomNumber
   marshalSize += 1;  // sourceLineID
   marshalSize += 1;  // transmitPriority
   if (transmitLineState != null)
       marshalSize += transmitLineState.getMarshalledSize();
   if (command != null)
       marshalSize += command.getMarshalledSize();
   if (masterIntercomReferenceID != null)
       marshalSize += masterIntercomReferenceID.getMarshalledSize();
   marshalSize += 2;  // masterIntercomNumber
   marshalSize += 2;  // masterChannelID
   marshalSize += 4;  // intercomParametersLength
   if (intercomParameters != null)
       marshalSize += intercomParameters.getMarshalledSize();

   return marshalSize;
}


/** Setter for {@link IntercomControlPdu#controlType}
  * @param pControlType new value of interest
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setControlType(IntercomControlControlType pControlType)
{
    controlType = pControlType;
    return this;
}
/** Getter for {@link IntercomControlPdu#controlType}
  * @return value of interest */
public IntercomControlControlType getControlType()
{
    return controlType; 
}

/** Setter for {@link IntercomControlPdu#communicationsChannelType}
  * @param pCommunicationsChannelType new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setCommunicationsChannelType(int pCommunicationsChannelType)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pCommunicationsChannelType >= 0 && pCommunicationsChannelType <= 255, "Value outside valid value space");
    communicationsChannelType = pCommunicationsChannelType;
    return this;
}
/** Getter for {@link IntercomControlPdu#communicationsChannelType}
  * @return value of interest */
public int getCommunicationsChannelType()
{
    return communicationsChannelType; 
}

/** Setter for {@link IntercomControlPdu#sourceEntityID}
  * @param pSourceEntityID new value of interest
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setSourceEntityID(EntityID pSourceEntityID)
{
    sourceEntityID = pSourceEntityID;
    return this;
}
/** Getter for {@link IntercomControlPdu#sourceEntityID}
  * @return value of interest */
public EntityID getSourceEntityID()
{
    return sourceEntityID;
}


/** Setter for {@link IntercomControlPdu#sourceIntercomNumber}
  * @param pSourceIntercomNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setSourceIntercomNumber(int pSourceIntercomNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pSourceIntercomNumber >= 0 && pSourceIntercomNumber <= 65535, "Value outside valid value space");
    sourceIntercomNumber = pSourceIntercomNumber;
    return this;
}
/** Getter for {@link IntercomControlPdu#sourceIntercomNumber}
  * @return value of interest */
public int getSourceIntercomNumber()
{
    return sourceIntercomNumber; 
}

/** Setter for {@link IntercomControlPdu#sourceLineID}
  * @param pSourceLineID new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setSourceLineID(int pSourceLineID)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pSourceLineID >= 0 && pSourceLineID <= 255, "Value outside valid value space");
    sourceLineID = pSourceLineID;
    return this;
}
/** Getter for {@link IntercomControlPdu#sourceLineID}
  * @return value of interest */
public int getSourceLineID()
{
    return sourceLineID; 
}

/** Setter for {@link IntercomControlPdu#transmitPriority}
  * @param pTransmitPriority new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setTransmitPriority(int pTransmitPriority)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pTransmitPriority >= 0 && pTransmitPriority <= 255, "Value outside valid value space");
    transmitPriority = pTransmitPriority;
    return this;
}
/** Getter for {@link IntercomControlPdu#transmitPriority}
  * @return value of interest */
public int getTransmitPriority()
{
    return transmitPriority; 
}

/** Setter for {@link IntercomControlPdu#transmitLineState}
  * @param pTransmitLineState new value of interest
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setTransmitLineState(IntercomControlTransmitLineState pTransmitLineState)
{
    transmitLineState = pTransmitLineState;
    return this;
}
/** Getter for {@link IntercomControlPdu#transmitLineState}
  * @return value of interest */
public IntercomControlTransmitLineState getTransmitLineState()
{
    return transmitLineState; 
}

/** Setter for {@link IntercomControlPdu#command}
  * @param pCommand new value of interest
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setCommand(IntercomControlCommand pCommand)
{
    command = pCommand;
    return this;
}
/** Getter for {@link IntercomControlPdu#command}
  * @return value of interest */
public IntercomControlCommand getCommand()
{
    return command; 
}

/** Setter for {@link IntercomControlPdu#masterIntercomReferenceID}
  * @param pMasterIntercomReferenceID new value of interest
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setMasterIntercomReferenceID(EntityID pMasterIntercomReferenceID)
{
    masterIntercomReferenceID = pMasterIntercomReferenceID;
    return this;
}
/** Getter for {@link IntercomControlPdu#masterIntercomReferenceID}
  * @return value of interest */
public EntityID getMasterIntercomReferenceID()
{
    return masterIntercomReferenceID;
}


/** Setter for {@link IntercomControlPdu#masterIntercomNumber}
  * @param pMasterIntercomNumber new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setMasterIntercomNumber(int pMasterIntercomNumber)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pMasterIntercomNumber >= 0 && pMasterIntercomNumber <= 65535, "Value outside valid value space");
    masterIntercomNumber = pMasterIntercomNumber;
    return this;
}
/** Getter for {@link IntercomControlPdu#masterIntercomNumber}
  * @return value of interest */
public int getMasterIntercomNumber()
{
    return masterIntercomNumber; 
}

/** Setter for {@link IntercomControlPdu#masterChannelID}
  * @param pMasterChannelID new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setMasterChannelID(int pMasterChannelID)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pMasterChannelID >= 0 && pMasterChannelID <= 65535, "Value outside valid value space");
    masterChannelID = pMasterChannelID;
    return this;
}
/** Getter for {@link IntercomControlPdu#masterChannelID}
  * @return value of interest */
public int getMasterChannelID()
{
    return masterChannelID; 
}

/** Setter for {@link IntercomControlPdu#intercomParameters}
  * @param pIntercomParameters new value of interest
  * @return same object to permit progressive setters */
public synchronized IntercomControlPdu setIntercomParameters(IntercomCommunicationsParameters pIntercomParameters)
{
    intercomParameters = pIntercomParameters;
    return this;
}
/** Getter for {@link IntercomControlPdu#intercomParameters}
  * @return value of interest */
public IntercomCommunicationsParameters getIntercomParameters()
{
    return intercomParameters;
}


/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    super.marshal(dos);

    {
       controlType.marshal(dos);
       dos.writeByte((byte) communicationsChannelType);
       sourceEntityID.marshal(dos);
       dos.writeShort((short) sourceIntercomNumber);
       dos.writeByte((byte) sourceLineID);
       dos.writeByte((byte) transmitPriority);
       transmitLineState.marshal(dos);
       command.marshal(dos);
       masterIntercomReferenceID.marshal(dos);
       dos.writeShort((short) masterIntercomNumber);
       dos.writeShort((short) masterChannelID);
       dos.writeInt(intercomParametersLength.intValue());
       intercomParameters.marshal(dos);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    uPosition += super.unmarshal(dis);


    {
        controlType = IntercomControlControlType.unmarshalEnum(dis);
        uPosition += controlType.getMarshalledSize();
        communicationsChannelType = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        uPosition += sourceEntityID.unmarshal(dis);
        sourceIntercomNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        sourceLineID = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        transmitPriority = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        transmitLineState = IntercomControlTransmitLineState.unmarshalEnum(dis);
        uPosition += transmitLineState.getMarshalledSize();
        command = IntercomControlCommand.unmarshalEnum(dis);
        uPosition += command.getMarshalledSize();
        uPosition += masterIntercomReferenceID.unmarshal(dis);
        masterIntercomNumber = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        masterChannelID = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        intercomParametersLength = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
        uPosition += intercomParameters.unmarshal(dis);
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   super.marshal(byteBuffer);
   controlType.marshal(byteBuffer);
   byteBuffer.put((byte) communicationsChannelType);
   sourceEntityID.marshal(byteBuffer);
   byteBuffer.putShort((short) sourceIntercomNumber);
   byteBuffer.put((byte) sourceLineID);
   byteBuffer.put((byte) transmitPriority);
   transmitLineState.marshal(byteBuffer);
   command.marshal(byteBuffer);
   masterIntercomReferenceID.marshal(byteBuffer);
   byteBuffer.putShort((short) masterIntercomNumber);
   byteBuffer.putShort((short) masterChannelID);
   byteBuffer.putInt(intercomParametersLength.intValue());
   intercomParameters.marshal(byteBuffer);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    super.unmarshal(byteBuffer);

    {
        controlType = IntercomControlControlType.unmarshalEnum(byteBuffer);
        communicationsChannelType = Byte.toUnsignedInt(byteBuffer.get());
        sourceEntityID.unmarshal(byteBuffer);
        sourceIntercomNumber = Short.toUnsignedInt(byteBuffer.getShort());
        sourceLineID = Byte.toUnsignedInt(byteBuffer.get());
        transmitPriority = Byte.toUnsignedInt(byteBuffer.get());
        transmitLineState = IntercomControlTransmitLineState.unmarshalEnum(byteBuffer);
        command = IntercomControlCommand.unmarshalEnum(byteBuffer);
        masterIntercomReferenceID.unmarshal(byteBuffer);
        masterIntercomNumber = Short.toUnsignedInt(byteBuffer.getShort());
        masterChannelID = Short.toUnsignedInt(byteBuffer.getShort());
        intercomParametersLength = UnsignedInteger.fromIntBits(byteBuffer.getInt());
        intercomParameters.unmarshal(byteBuffer);
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = RadioCommunicationsFamilyPdu.fromBufferToMap(byteBuffer);

    map.put("controlType", IntercomControlControlType.unmarshalEnum(byteBuffer).getValue());
    map.put("communicationsChannelType", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("sourceEntityID", EntityID.fromBufferToMap(byteBuffer));
    map.put("sourceIntercomNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("sourceLineID", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("transmitPriority", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("transmitLineState", IntercomControlTransmitLineState.unmarshalEnum(byteBuffer).getValue());
    map.put("command", IntercomControlCommand.unmarshalEnum(byteBuffer).getValue());
    map.put("masterIntercomReferenceID", EntityID.fromBufferToMap(byteBuffer));
    map.put("masterIntercomNumber", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("masterChannelID", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("intercomParametersLength", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    map.put("intercomParameters", IntercomCommunicationsParameters.fromBufferToMap(byteBuffer));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    RadioCommunicationsFamilyPdu.fromMapToBuffer(map, byteBuffer);
    IntercomControlControlType.getEnumForValue(((Number) map.get("controlType")).intValue()).marshal(byteBuffer);
    byteBuffer.put(((Number) map.get("communicationsChannelType")).byteValue());
    EntityID.fromMapToBuffer((PduMap) map.get("sourceEntityID"), byteBuffer);
    byteBuffer.putShort(((Number) map.get("sourceIntercomNumber")).shortValue());
    byteBuffer.put(((Number) map.get("sourceLineID")).byteValue());
    byteBuffer.put(((Number) map.get("transmitPriority")).byteValue());
    IntercomControlTransmitLineState.getEnumForValue(((Number) map.get("transmitLineState")).intValue()).marshal(byteBuffer);
    IntercomControlCommand.getEnumForValue(((Number) map.get("command")).intValue()).marshal(byteBuffer);
    EntityID.fromMapToBuffer((PduMap) map.get("masterIntercomReferenceID"), byteBuffer);
    byteBuffer.putShort(((Number) map.get("masterIntercomNumber")).shortValue());
    byteBuffer.putShort(((Number) map.get("masterChannelID")).shortValue());
    byteBuffer.putInt(((Number) map.get("intercomParametersLength")).intValue());
    IntercomCommunicationsParameters.fromMapToBuffer((PduMap) map.get("intercomParameters"), byteBuffer);
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += RadioCommunicationsFamilyPdu.getMarshalledSize(map);
    marshalSize += IntercomControlControlType.getEnumForValue(((Number) map.get("controlType")).intValue()).getMarshalledSize();
    marshalSize += 1;  // communicationsChannelType
    marshalSize += EntityID.getMarshalledSize((PduMap) map.get("sourceEntityID"));
    marshalSize += 2;  // sourceIntercomNumber
    marshalSize += 1;  // sourceLineID
    marshalSize += 1;  // transmitPriority
    marshalSize += IntercomControlTransmitLineState.getEnumForValue(((Number) map.get("transmitLineState")).intValue()).getMarshalledSize();
    marshalSize += IntercomControlCommand.getEnumForValue(((Number) map.get("command")).intValue()).getMarshalledSize();
    marshalSize += EntityID.getMarshalledSize((PduMap) map.get("masterIntercomReferenceID"));
    marshalSize += 2;  // masterIntercomNumber
    marshalSize += 2;  // masterChannelID
    marshalSize += 4;  // intercomParametersLength
    marshalSize += IntercomCommunicationsParameters.getMarshalledSize((PduMap) map.get("intercomParameters"));

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public synchronized boolean equalsImpl(Object obj)
 {
     final IntercomControlPdu rhs = (IntercomControlPdu)obj;

     if( ! (controlType == rhs.controlType)) return false;
     if( ! (communicationsChannelType == rhs.communicationsChannelType)) return false;
     if( ! Objects.equals(sourceEntityID, rhs.sourceEntityID) ) return false;
     if( ! (sourceIntercomNumber == rhs.sourceIntercomNumber)) return false;
     if( ! (sourceLineID == rhs.sourceLineID)) return false;
     if( ! (transmitPriority == rhs.transmitPriority)) return false;
     if( ! (transmitLineState == rhs.transmitLineState)) return false;
     if( ! (command == rhs.command)) return false;
     if( ! Objects.equals(masterIntercomReferenceID, rhs.masterIntercomReferenceID) ) return false;
     if( ! (masterIntercomNumber == rhs.masterIntercomNumber)) return false;
     if( ! (masterChannelID == rhs.masterChannelID)) return false;
     if( ! Objects.equals(intercomParameters, rhs.intercomParameters) ) return false;
    return super.equalsImpl(rhs);
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(super.toString());
    sb.append(" controlType:").append(controlType); // writeOneToString
    sb.append(" communicationsChannelType:").append(communicationsChannelType); // writeOneToString
    sb.append(" sourceEntityID:").append(sourceEntityID); // writeOneToString
    sb.append(" sourceIntercomNumber:").append(sourceIntercomNumber); // writeOneToString
    sb.append(" sourceLineID:").append(sourceLineID); // writeOneToString
    sb.append(" transmitPriority:").append(transmitPriority); // writeOneToString
    sb.append(" transmitLineState:").append(transmitLineState); // writeOneToString
    sb.append(" command:").append(command); // writeOneToString
    sb.append(" masterIntercomReferenceID:").append(masterIntercomReferenceID); // writeOneToString
    sb.append(" masterIntercomNumber:").append(masterIntercomNumber); // writeOneToString
    sb.append(" masterChannelID:").append(masterChannelID); // writeOneToString
    sb.append(" intercomParameters:").append(intercomParameters); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.controlType,
	                     this.communicationsChannelType,
	                     this.sourceEntityID,
	                     this.sourceIntercomNumber,
	                     this.sourceLineID,
	                     this.transmitPriority,
	                     this.transmitLineState,
	                     this.command,
	                     this.masterIntercomReferenceID,
	                     this.masterIntercomNumber,
	                     this.masterChannelID,
	                     this.intercomParametersLength,
	                     this.intercomParameters);
 }
} // end of IntercomControlPdu
