/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;

/**
 * indicate weapons (munitions) previously communicated via the Munition record. Section 6.2.61 
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class MunitionReload extends Object implements Serializable, Marshaller
{
   /**  This field shall identify the entity type of the munition. See section 6.2.30. */
   protected EntityType  munitionType = new EntityType(); 

   /** The station or launcher to which the munition is assigned. See Annex I 
   Value space: uint32 */
   protected UnsignedInteger station = UnsignedInteger.ZERO;

   /** The standard quantity of this munition type normally loaded at this station/launcher if a station/launcher is specified. 
   Value space: uint16 */
   protected int standardQuantity;

   /** The maximum quantity of this munition type that this station/launcher is capable of holding when a station/launcher is specified  
   Value space: uint16 */
   protected int maximumQuantity;

   /** numer of seconds of sim time required to reload the std qty 
   Value space: uint32 */
   protected UnsignedInteger standardQuantityReloadTime = UnsignedInteger.ZERO;

   /** The number of seconds of sim time required to reload the max possible quantity 
   Value space: uint32 */
   protected UnsignedInteger maximumQuantityReloadTime = UnsignedInteger.ZERO;


/** Constructor creates and configures a new instance object */
 public MunitionReload()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   if (munitionType != null)
       marshalSize += munitionType.getMarshalledSize();
   marshalSize += 4;  // station
   marshalSize += 2;  // standardQuantity
   marshalSize += 2;  // maximumQuantity
   marshalSize += 4;  // standardQuantityReloadTime
   marshalSize += 4;  // maximumQuantityReloadTime

   return marshalSize;
}


/** Setter for {@link MunitionReload#munitionType}
  * @param pMunitionType new value of interest
  * @return same object to permit progressive setters */
public synchronized MunitionReload setMunitionType(EntityType pMunitionType)
{
    munitionType = pMunitionType;
    return this;
}
/** Getter for {@link MunitionReload#munitionType}
  * @return value of interest */
public EntityType getMunitionType()
{
    return munitionType;
}


/** Setter for {@link MunitionReload#station}
  * @param pStation new value of interest. Value space uint32
  * @return same object to permit progressive setters */
public synchronized MunitionReload setStation(UnsignedInteger pStation)
{
    station = pStation;
    return this;
}
/** Getter for {@link MunitionReload#station}
  * @return value of interest */
public UnsignedInteger getStation()
{
    return station; 
}

/** Setter for {@link MunitionReload#standardQuantity}
  * @param pStandardQuantity new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized MunitionReload setStandardQuantity(int pStandardQuantity)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pStandardQuantity >= 0 && pStandardQuantity <= 65535, "Value outside valid value space");
    standardQuantity = pStandardQuantity;
    return this;
}
/** Getter for {@link MunitionReload#standardQuantity}
  * @return value of interest */
public int getStandardQuantity()
{
    return standardQuantity; 
}

/** Setter for {@link MunitionReload#maximumQuantity}
  * @param pMaximumQuantity new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized MunitionReload setMaximumQuantity(int pMaximumQuantity)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pMaximumQuantity >= 0 && pMaximumQuantity <= 65535, "Value outside valid value space");
    maximumQuantity = pMaximumQuantity;
    return this;
}
/** Getter for {@link MunitionReload#maximumQuantity}
  * @return value of interest */
public int getMaximumQuantity()
{
    return maximumQuantity; 
}

/** Setter for {@link MunitionReload#standardQuantityReloadTime}
  * @param pStandardQuantityReloadTime new value of interest. Value space uint32
  * @return same object to permit progressive setters */
public synchronized MunitionReload setStandardQuantityReloadTime(UnsignedInteger pStandardQuantityReloadTime)
{
    standardQuantityReloadTime = pStandardQuantityReloadTime;
    return this;
}
/** Getter for {@link MunitionReload#standardQuantityReloadTime}
  * @return value of interest */
public UnsignedInteger getStandardQuantityReloadTime()
{
    return standardQuantityReloadTime; 
}

/** Setter for {@link MunitionReload#maximumQuantityReloadTime}
  * @param pMaximumQuantityReloadTime new value of interest. Value space uint32
  * @return same object to permit progressive setters */
public synchronized MunitionReload setMaximumQuantityReloadTime(UnsignedInteger pMaximumQuantityReloadTime)
{
    maximumQuantityReloadTime = pMaximumQuantityReloadTime;
    return this;
}
/** Getter for {@link MunitionReload#maximumQuantityReloadTime}
  * @return value of interest */
public UnsignedInteger getMaximumQuantityReloadTime()
{
    return maximumQuantityReloadTime; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{

    {
       munitionType.marshal(dos);
       dos.writeInt(station.intValue());
       dos.writeShort((short) standardQuantity);
       dos.writeShort((short) maximumQuantity);
       dos.writeInt(standardQuantityReloadTime.intValue());
       dos.writeInt(maximumQuantityReloadTime.intValue());
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;

    {
        uPosition += munitionType.unmarshal(dis);
        station = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
        standardQuantity = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        maximumQuantity = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        standardQuantityReloadTime = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
        maximumQuantityReloadTime = UnsignedInteger.fromIntBits(dis.readInt());
        uPosition += 4;
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   munitionType.marshal(byteBuffer);
   byteBuffer.putInt(station.intValue());
   byteBuffer.putShort((short) standardQuantity);
   byteBuffer.putShort((short) maximumQuantity);
   byteBuffer.putInt(standardQuantityReloadTime.intValue());
   byteBuffer.putInt(maximumQuantityReloadTime.intValue());
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    {
        munitionType.unmarshal(byteBuffer);
        station = UnsignedInteger.fromIntBits(byteBuffer.getInt());
        standardQuantity = Short.toUnsignedInt(byteBuffer.getShort());
        maximumQuantity = Short.toUnsignedInt(byteBuffer.getShort());
        standardQuantityReloadTime = UnsignedInteger.fromIntBits(byteBuffer.getInt());
        maximumQuantityReloadTime = UnsignedInteger.fromIntBits(byteBuffer.getInt());
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = new PduMap();

    map.put("munitionType", EntityType.fromBufferToMap(byteBuffer));
    map.put("station", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    map.put("standardQuantity", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("maximumQuantity", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("standardQuantityReloadTime", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    map.put("maximumQuantityReloadTime", UnsignedInteger.fromIntBits(byteBuffer.getInt()));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    EntityType.fromMapToBuffer((PduMap) map.get("munitionType"), byteBuffer);
    byteBuffer.putInt(((Number) map.get("station")).intValue());
    byteBuffer.putShort(((Number) map.get("standardQuantity")).shortValue());
    byteBuffer.putShort(((Number) map.get("maximumQuantity")).shortValue());
    byteBuffer.putInt(((Number) map.get("standardQuantityReloadTime")).intValue());
    byteBuffer.putInt(((Number) map.get("maximumQuantityReloadTime")).intValue());
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += EntityType.getMarshalledSize((PduMap) map.get("munitionType"));
    marshalSize += 4;  // station
    marshalSize += 2;  // standardQuantity
    marshalSize += 2;  // maximumQuantity
    marshalSize += 4;  // standardQuantityReloadTime
    marshalSize += 4;  // maximumQuantityReloadTime

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

 /**
  * Compare all fields that contribute to the state, ignoring
  * transient and static fields, for <code>this</code> and the supplied object
  * @param obj the object to compare to
  * @return true if the objects are equal, false otherwise.
  */
 public synchronized boolean equalsImpl(Object obj)
 {
     final MunitionReload rhs = (MunitionReload)obj;

     if( ! Objects.equals(munitionType, rhs.munitionType) ) return false;
     if( ! (station == rhs.station)) return false;
     if( ! (standardQuantity == rhs.standardQuantity)) return false;
     if( ! (maximumQuantity == rhs.maximumQuantity)) return false;
     if( ! (standardQuantityReloadTime == rhs.standardQuantityReloadTime)) return false;
     if( ! (maximumQuantityReloadTime == rhs.maximumQuantityReloadTime)) return false;
    return true;
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" munitionType:").append(munitionType); // writeOneToString
    sb.append(" station:").append(station); // writeOneToString
    sb.append(" standardQuantity:").append(standardQuantity); // writeOneToString
    sb.append(" maximumQuantity:").append(maximumQuantity); // writeOneToString
    sb.append(" standardQuantityReloadTime:").append(standardQuantityReloadTime); // writeOneToString
    sb.append(" maximumQuantityReloadTime:").append(maximumQuantityReloadTime); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.munitionType,
	                     this.station,
	                     this.standardQuantity,
	                     this.maximumQuantity,
	                     this.standardQuantityReloadTime,
	                     this.maximumQuantityReloadTime);
 }
} // end of MunitionReload
