/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;

/**
 * The superclass for all PDUs except LiveEntity. This incorporates the PduHeader record, section 7.2.2
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public abstract class PduBase extends Pdu implements Serializable, Marshaller
{
   /** PDU Status Record. Described in 6.2.67. This field is not present in earlier DIS versions  */
   protected PduStatus  pduStatus = new PduStatus(); 

   /** zero-filled array of padding bits for byte alignment and consistent sizing of PDU data 
   Value space: uint8 */
   protected int paddingHeader = (int) 0;


/** Constructor creates and configures a new instance object */
 public PduBase()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   if (pduStatus != null)
       marshalSize += pduStatus.getMarshalledSize();
   marshalSize += 1;  // paddingHeader

   return marshalSize;
}


/** Setter for {@link PduBase#pduStatus}
  * @param pPduStatus new value of interest
  * @return same object to permit progressive setters */
public synchronized PduBase setPduStatus(PduStatus pPduStatus)
{
    pduStatus = pPduStatus;
    return this;
}
/** Getter for {@link PduBase#pduStatus}
  * @return value of interest */
public PduStatus getPduStatus()
{
    return pduStatus;
}


/** Setter for {@link PduBase#paddingHeader}
  * @param pPaddingHeader new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized PduBase setPaddingHeader(int pPaddingHeader)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pPaddingHeader >= 0 && pPaddingHeader <= 255, "Value outside valid value space");
    paddingHeader = pPaddingHeader;
    return this;
}
/** Getter for {@link PduBase#paddingHeader}
  * @return value of interest */
public int getPaddingHeader()
{
    return paddingHeader; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    super.marshal(dos);

    {
       pduStatus.marshal(dos);
       dos.writeByte((byte) paddingHeader);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    uPosition += super.unmarshal(dis);


    {
        uPosition += pduStatus.unmarshal(dis);
        paddingHeader = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   super.marshal(byteBuffer);
   pduStatus.marshal(byteBuffer);
   byteBuffer.put((byte) paddingHeader);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    super.unmarshal(byteBuffer);

    {
        pduStatus.unmarshal(byteBuffer);
        paddingHeader = Byte.toUnsignedInt(byteBuffer.get());
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = Pdu.fromBufferToMap(byteBuffer);

    map.put("pduStatus", PduStatus.fromBufferToMap(byteBuffer));
    map.put("paddingHeader", Byte.toUnsignedInt(byteBuffer.get()));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    Pdu.fromMapToBuffer(map, byteBuffer);
    PduStatus.fromMapToBuffer((PduMap) map.get("pduStatus"), byteBuffer);
    byteBuffer.put(((Number) map.get("paddingHeader")).byteValue());
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += Pdu.getMarshalledSize(map);
    marshalSize += PduStatus.getMarshalledSize((PduMap) map.get("pduStatus"));
    marshalSize += 1;  // paddingHeader

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public synchronized boolean equalsImpl(Object obj)
 {
     final PduBase rhs = (PduBase)obj;

     if( ! Objects.equals(pduStatus, rhs.pduStatus) ) return false;
     if( ! (paddingHeader == rhs.paddingHeader)) return false;
    return super.equalsImpl(rhs);
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(super.toString());
    sb.append(" pduStatus:").append(pduStatus); // writeOneToString
    sb.append(" paddingHeader:").append(paddingHeader); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.pduStatus,
	                     this.paddingHeader);
 }
} // end of PduBase
