/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;

/**
 * Identifies the type of radio. Section 6.2.71
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class RadioType extends Object implements Serializable, Marshaller
{
   /** Kind of entity uid 7 */
   protected EntityKind entityKind = EntityKind.RADIO;

   /** Domain of entity (air, surface, subsurface, space, etc.) 
   Value space: uint8 */
   protected int domain;

   /** country to which the design of the entity is attributed uid 29 */
   protected Country country = Country.values()[0];

   /** category of entity uid 22 */
   protected RadioCategory category = RadioCategory.values()[0];

   /** specific info based on subcategory field uid 23 */
   protected RadioSubcategory subcategory = RadioSubcategory.values()[0];

   /** specific is an undescribed parameter...
   Value space: uint8 */
   protected int specific;

   /** extra is an undescribed parameter...
   Value space: uint8 */
   protected int extra;


/** Constructor creates and configures a new instance object */
 public RadioType()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   if (entityKind != null)
       marshalSize += entityKind.getMarshalledSize();
   marshalSize += 1;  // domain
   if (country != null)
       marshalSize += country.getMarshalledSize();
   if (category != null)
       marshalSize += category.getMarshalledSize();
   if (subcategory != null)
       marshalSize += subcategory.getMarshalledSize();
   marshalSize += 1;  // specific
   marshalSize += 1;  // extra

   return marshalSize;
}


/** Setter for {@link RadioType#entityKind}
  * @param pEntityKind new value of interest
  * @return same object to permit progressive setters */
public synchronized RadioType setEntityKind(EntityKind pEntityKind)
{
    entityKind = pEntityKind;
    return this;
}
/** Getter for {@link RadioType#entityKind}
  * @return value of interest */
public EntityKind getEntityKind()
{
    return entityKind; 
}

/** Setter for {@link RadioType#domain}
  * @param pDomain new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized RadioType setDomain(int pDomain)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pDomain >= 0 && pDomain <= 255, "Value outside valid value space");
    domain = pDomain;
    return this;
}
/** Getter for {@link RadioType#domain}
  * @return value of interest */
public int getDomain()
{
    return domain; 
}

/** Setter for {@link RadioType#country}
  * @param pCountry new value of interest
  * @return same object to permit progressive setters */
public synchronized RadioType setCountry(Country pCountry)
{
    country = pCountry;
    return this;
}
/** Getter for {@link RadioType#country}
  * @return value of interest */
public Country getCountry()
{
    return country; 
}

/** Setter for {@link RadioType#category}
  * @param pCategory new value of interest
  * @return same object to permit progressive setters */
public synchronized RadioType setCategory(RadioCategory pCategory)
{
    category = pCategory;
    return this;
}
/** Getter for {@link RadioType#category}
  * @return value of interest */
public RadioCategory getCategory()
{
    return category; 
}

/** Setter for {@link RadioType#subcategory}
  * @param pSubcategory new value of interest
  * @return same object to permit progressive setters */
public synchronized RadioType setSubcategory(RadioSubcategory pSubcategory)
{
    subcategory = pSubcategory;
    return this;
}
/** Getter for {@link RadioType#subcategory}
  * @return value of interest */
public RadioSubcategory getSubcategory()
{
    return subcategory; 
}

/** Setter for {@link RadioType#specific}
  * @param pSpecific new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized RadioType setSpecific(int pSpecific)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pSpecific >= 0 && pSpecific <= 255, "Value outside valid value space");
    specific = pSpecific;
    return this;
}
/** Getter for {@link RadioType#specific}
  * @return value of interest */
public int getSpecific()
{
    return specific; 
}

/** Setter for {@link RadioType#extra}
  * @param pExtra new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized RadioType setExtra(int pExtra)
{
    // Checking value is in value space uint8
    Preconditions.checkArgument(pExtra >= 0 && pExtra <= 255, "Value outside valid value space");
    extra = pExtra;
    return this;
}
/** Getter for {@link RadioType#extra}
  * @return value of interest */
public int getExtra()
{
    return extra; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{

    {
       entityKind.marshal(dos);
       dos.writeByte((byte) domain);
       country.marshal(dos);
       category.marshal(dos);
       subcategory.marshal(dos);
       dos.writeByte((byte) specific);
       dos.writeByte((byte) extra);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;

    {
        entityKind = EntityKind.unmarshalEnum(dis);
        uPosition += entityKind.getMarshalledSize();
        domain = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        country = Country.unmarshalEnum(dis);
        uPosition += country.getMarshalledSize();
        category = RadioCategory.unmarshalEnum(dis);
        uPosition += category.getMarshalledSize();
        subcategory = RadioSubcategory.unmarshalEnum(dis);
        uPosition += subcategory.getMarshalledSize();
        specific = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        extra = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   entityKind.marshal(byteBuffer);
   byteBuffer.put((byte) domain);
   country.marshal(byteBuffer);
   category.marshal(byteBuffer);
   subcategory.marshal(byteBuffer);
   byteBuffer.put((byte) specific);
   byteBuffer.put((byte) extra);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    {
        entityKind = EntityKind.unmarshalEnum(byteBuffer);
        domain = Byte.toUnsignedInt(byteBuffer.get());
        country = Country.unmarshalEnum(byteBuffer);
        category = RadioCategory.unmarshalEnum(byteBuffer);
        subcategory = RadioSubcategory.unmarshalEnum(byteBuffer);
        specific = Byte.toUnsignedInt(byteBuffer.get());
        extra = Byte.toUnsignedInt(byteBuffer.get());
    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = new PduMap();

    map.put("entityKind", EntityKind.unmarshalEnum(byteBuffer).getValue());
    map.put("domain", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("country", Country.unmarshalEnum(byteBuffer).getValue());
    map.put("category", RadioCategory.unmarshalEnum(byteBuffer).getValue());
    map.put("subcategory", RadioSubcategory.unmarshalEnum(byteBuffer).getValue());
    map.put("specific", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("extra", Byte.toUnsignedInt(byteBuffer.get()));
    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    EntityKind.getEnumForValue(((Number) map.get("entityKind")).intValue()).marshal(byteBuffer);
    byteBuffer.put(((Number) map.get("domain")).byteValue());
    Country.getEnumForValue(((Number) map.get("country")).intValue()).marshal(byteBuffer);
    RadioCategory.getEnumForValue(((Number) map.get("category")).intValue()).marshal(byteBuffer);
    RadioSubcategory.getEnumForValue(((Number) map.get("subcategory")).intValue()).marshal(byteBuffer);
    byteBuffer.put(((Number) map.get("specific")).byteValue());
    byteBuffer.put(((Number) map.get("extra")).byteValue());
}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += EntityKind.getEnumForValue(((Number) map.get("entityKind")).intValue()).getMarshalledSize();
    marshalSize += 1;  // domain
    marshalSize += Country.getEnumForValue(((Number) map.get("country")).intValue()).getMarshalledSize();
    marshalSize += RadioCategory.getEnumForValue(((Number) map.get("category")).intValue()).getMarshalledSize();
    marshalSize += RadioSubcategory.getEnumForValue(((Number) map.get("subcategory")).intValue()).getMarshalledSize();
    marshalSize += 1;  // specific
    marshalSize += 1;  // extra

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

 /**
  * Compare all fields that contribute to the state, ignoring
  * transient and static fields, for <code>this</code> and the supplied object
  * @param obj the object to compare to
  * @return true if the objects are equal, false otherwise.
  */
 public synchronized boolean equalsImpl(Object obj)
 {
     final RadioType rhs = (RadioType)obj;

     if( ! (entityKind == rhs.entityKind)) return false;
     if( ! (domain == rhs.domain)) return false;
     if( ! (country == rhs.country)) return false;
     if( ! (category == rhs.category)) return false;
     if( ! (subcategory == rhs.subcategory)) return false;
     if( ! (specific == rhs.specific)) return false;
     if( ! (extra == rhs.extra)) return false;
    return true;
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" entityKind:").append(entityKind); // writeOneToString
    sb.append(" domain:").append(domain); // writeOneToString
    sb.append(" country:").append(country); // writeOneToString
    sb.append(" category:").append(category); // writeOneToString
    sb.append(" subcategory:").append(subcategory); // writeOneToString
    sb.append(" specific:").append(specific); // writeOneToString
    sb.append(" extra:").append(extra); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.entityKind,
	                     this.domain,
	                     this.country,
	                     this.category,
	                     this.subcategory,
	                     this.specific,
	                     this.extra);
 }
} // end of RadioType
