/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;
import java.nio.ByteBuffer;

/**
 * 7.6.6 Certain supplemental information on an entity’s physical state and emissions. See 5.7.7
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class SEESPdu extends DistributedEmissionsRegenerationFamilyPdu implements Serializable, Marshaller
{

   /** The name of this PDU type */
   public static final String NAME = "SEESPdu";
   
   /** Originating entity ID provides a unique identifier */
   protected EntityID  orginatingEntityID = new EntityID(); 

   /** IR Signature representation index 
   Value space: uint16 */
   protected int infraredSignatureRepresentationIndex;

   /** acoustic Signature representation index 
   Value space: uint16 */
   protected int acousticSignatureRepresentationIndex;

   /** radar cross section representation index 
   Value space: uint16 */
   protected int radarCrossSectionSignatureRepresentationIndex;

   /** how many propulsion systems 
   Value space: uint16 */
   protected int numberOfPropulsionSystems;

   /** how many vectoring nozzle systems 
   Value space: uint16 */
   protected int numberOfVectoringNozzleSystems;

   /** variable length list of propulsion system data */
   protected List< PropulsionSystemData > propulsionSystemData = new ArrayList<>();
 
   /** variable length list of vectoring system data */
   protected List< VectoringNozzleSystem > vectoringSystemData = new ArrayList<>();
 

/** Constructor creates and configures a new instance object */
 public SEESPdu()
 {
    setPduType( DisPduType.SUPPLEMENTAL_EMISSION_ENTITY_STATE );
 }
/** copy method creates a deep copy of current object using preferred marshalling method
 * @return deep copy of PDU */
 public synchronized SEESPdu copy()
 {
     return copyDataOutputStream();
 }
/** Creates a "deep copy" of current object using ByteBuffer methods.
 * @return deep copy of PDU */
 public synchronized SEESPdu copyByteBuffer()
 {
     SEESPdu newCopy = new SEESPdu();
     ByteBuffer byteBuffer = ByteBuffer.allocate(400);
     try
     {
         this.marshal(byteBuffer);      // working
         newCopy.unmarshal(byteBuffer); // not working
     }
     catch (Exception e)
     {
         System.err.println("SEESPdu deep copy() marshall/unmarshall ByteBuffer exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
     return newCopy;
 }

/** byteArrayOutputStream (baos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
/** dataOutputStream (dos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected DataOutputStream      dataOutputStream      = new DataOutputStream(byteArrayOutputStream);

/** copy method creates a deep copy of current object using DataOutputStream methods.
 * @return deep copy of PDU */
 public synchronized SEESPdu copyDataOutputStream()
 {
     SEESPdu newCopy = new SEESPdu();
     try
     {
         this.marshal(dataOutputStream);
         byte[] byteArrayDOS = byteArrayOutputStream.toByteArray();
         newCopy.unmarshal(ByteBuffer.wrap(byteArrayDOS));
     }
     catch (Exception e)
     {
         System.err.println("SEESPdu deep copy() marshall/unmarshall DataOutputStream exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
        try
        {
                 dataOutputStream.flush();
            byteArrayOutputStream.flush();
            byteArrayOutputStream.reset();
        }
        catch (IOException ioe)
        {
            System.err.println("SEESPdu copyDataOutputStream() flush IOException: " + ioe.getMessage());
        }
     return newCopy;
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   if (orginatingEntityID != null)
       marshalSize += orginatingEntityID.getMarshalledSize();
   marshalSize += 2;  // infraredSignatureRepresentationIndex
   marshalSize += 2;  // acousticSignatureRepresentationIndex
   marshalSize += 2;  // radarCrossSectionSignatureRepresentationIndex
   marshalSize += 2;  // numberOfPropulsionSystems
   marshalSize += 2;  // numberOfVectoringNozzleSystems
   if (propulsionSystemData != null)
       for (int idx=0; idx < propulsionSystemData.size(); idx++)
       {
            PropulsionSystemData listElement = propulsionSystemData.get(idx);
            marshalSize += listElement.getMarshalledSize();
       }
   if (vectoringSystemData != null)
       for (int idx=0; idx < vectoringSystemData.size(); idx++)
       {
            VectoringNozzleSystem listElement = vectoringSystemData.get(idx);
            marshalSize += listElement.getMarshalledSize();
       }

   return marshalSize;
}


/** Setter for {@link SEESPdu#orginatingEntityID}
  * @param pOrginatingEntityID new value of interest
  * @return same object to permit progressive setters */
public synchronized SEESPdu setOrginatingEntityID(EntityID pOrginatingEntityID)
{
    orginatingEntityID = pOrginatingEntityID;
    return this;
}
/** Getter for {@link SEESPdu#orginatingEntityID}
  * @return value of interest */
public EntityID getOrginatingEntityID()
{
    return orginatingEntityID;
}


/** Setter for {@link SEESPdu#infraredSignatureRepresentationIndex}
  * @param pInfraredSignatureRepresentationIndex new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized SEESPdu setInfraredSignatureRepresentationIndex(int pInfraredSignatureRepresentationIndex)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pInfraredSignatureRepresentationIndex >= 0 && pInfraredSignatureRepresentationIndex <= 65535, "Value outside valid value space");
    infraredSignatureRepresentationIndex = pInfraredSignatureRepresentationIndex;
    return this;
}
/** Getter for {@link SEESPdu#infraredSignatureRepresentationIndex}
  * @return value of interest */
public int getInfraredSignatureRepresentationIndex()
{
    return infraredSignatureRepresentationIndex; 
}

/** Setter for {@link SEESPdu#acousticSignatureRepresentationIndex}
  * @param pAcousticSignatureRepresentationIndex new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized SEESPdu setAcousticSignatureRepresentationIndex(int pAcousticSignatureRepresentationIndex)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pAcousticSignatureRepresentationIndex >= 0 && pAcousticSignatureRepresentationIndex <= 65535, "Value outside valid value space");
    acousticSignatureRepresentationIndex = pAcousticSignatureRepresentationIndex;
    return this;
}
/** Getter for {@link SEESPdu#acousticSignatureRepresentationIndex}
  * @return value of interest */
public int getAcousticSignatureRepresentationIndex()
{
    return acousticSignatureRepresentationIndex; 
}

/** Setter for {@link SEESPdu#radarCrossSectionSignatureRepresentationIndex}
  * @param pRadarCrossSectionSignatureRepresentationIndex new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized SEESPdu setRadarCrossSectionSignatureRepresentationIndex(int pRadarCrossSectionSignatureRepresentationIndex)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pRadarCrossSectionSignatureRepresentationIndex >= 0 && pRadarCrossSectionSignatureRepresentationIndex <= 65535, "Value outside valid value space");
    radarCrossSectionSignatureRepresentationIndex = pRadarCrossSectionSignatureRepresentationIndex;
    return this;
}
/** Getter for {@link SEESPdu#radarCrossSectionSignatureRepresentationIndex}
  * @return value of interest */
public int getRadarCrossSectionSignatureRepresentationIndex()
{
    return radarCrossSectionSignatureRepresentationIndex; 
}

/** Setter for {@link SEESPdu#propulsionSystemData}
  * @param pPropulsionSystemData new value of interest
  * @return same object to permit progressive setters */
public synchronized SEESPdu setPropulsionSystemData(List<PropulsionSystemData> pPropulsionSystemData)
{
    propulsionSystemData = pPropulsionSystemData;
    return this;
}
/** Getter for {@link SEESPdu#propulsionSystemData}
  * @return value of interest */
public List<PropulsionSystemData> getPropulsionSystemData()
{
    return propulsionSystemData; 
}

/** Setter for {@link SEESPdu#vectoringSystemData}
  * @param pVectoringSystemData new value of interest
  * @return same object to permit progressive setters */
public synchronized SEESPdu setVectoringSystemData(List<VectoringNozzleSystem> pVectoringSystemData)
{
    vectoringSystemData = pVectoringSystemData;
    return this;
}
/** Getter for {@link SEESPdu#vectoringSystemData}
  * @return value of interest */
public List<VectoringNozzleSystem> getVectoringSystemData()
{
    return vectoringSystemData; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    super.marshal(dos);

    {
       orginatingEntityID.marshal(dos);
       dos.writeShort((short) infraredSignatureRepresentationIndex);
       dos.writeShort((short) acousticSignatureRepresentationIndex);
       dos.writeShort((short) radarCrossSectionSignatureRepresentationIndex);
       dos.writeShort(propulsionSystemData.size());
       dos.writeShort(vectoringSystemData.size());

       for (int idx = 0; idx < propulsionSystemData.size(); idx++)
       {
            PropulsionSystemData aPropulsionSystemData = propulsionSystemData.get(idx);
            aPropulsionSystemData.marshal(dos);
       }


       for (int idx = 0; idx < vectoringSystemData.size(); idx++)
       {
            VectoringNozzleSystem aVectoringNozzleSystem = vectoringSystemData.get(idx);
            aVectoringNozzleSystem.marshal(dos);
       }

    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    uPosition += super.unmarshal(dis);


    {
        uPosition += orginatingEntityID.unmarshal(dis);
        infraredSignatureRepresentationIndex = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        acousticSignatureRepresentationIndex = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        radarCrossSectionSignatureRepresentationIndex = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        numberOfPropulsionSystems = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        numberOfVectoringNozzleSystems = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        for (int idx = 0; idx < ((Number) numberOfPropulsionSystems).intValue(); idx++)
        {
            PropulsionSystemData anX = new PropulsionSystemData();
            uPosition += anX.unmarshal(dis);
            propulsionSystemData.add(anX);
        }

        for (int idx = 0; idx < ((Number) numberOfVectoringNozzleSystems).intValue(); idx++)
        {
            VectoringNozzleSystem anX = new VectoringNozzleSystem();
            uPosition += anX.unmarshal(dis);
            vectoringSystemData.add(anX);
        }

    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   super.marshal(byteBuffer);
   orginatingEntityID.marshal(byteBuffer);
   byteBuffer.putShort((short) infraredSignatureRepresentationIndex);
   byteBuffer.putShort((short) acousticSignatureRepresentationIndex);
   byteBuffer.putShort((short) radarCrossSectionSignatureRepresentationIndex);
   byteBuffer.putShort( (short)propulsionSystemData.size());
   byteBuffer.putShort( (short)vectoringSystemData.size());

   for (int idx = 0; idx < propulsionSystemData.size(); idx++)
   {
        PropulsionSystemData aPropulsionSystemData = propulsionSystemData.get(idx);
        aPropulsionSystemData.marshal(byteBuffer);
   }


   for (int idx = 0; idx < vectoringSystemData.size(); idx++)
   {
        VectoringNozzleSystem aVectoringNozzleSystem = vectoringSystemData.get(idx);
        aVectoringNozzleSystem.marshal(byteBuffer);
   }

}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    super.unmarshal(byteBuffer);

    {
        orginatingEntityID.unmarshal(byteBuffer);
        infraredSignatureRepresentationIndex = Short.toUnsignedInt(byteBuffer.getShort());
        acousticSignatureRepresentationIndex = Short.toUnsignedInt(byteBuffer.getShort());
        radarCrossSectionSignatureRepresentationIndex = Short.toUnsignedInt(byteBuffer.getShort());
        numberOfPropulsionSystems = Short.toUnsignedInt(byteBuffer.getShort());
        numberOfVectoringNozzleSystems = Short.toUnsignedInt(byteBuffer.getShort());
        for (int idx = 0; idx < ((Number) numberOfPropulsionSystems).intValue(); idx++)
        {
            PropulsionSystemData anX = new PropulsionSystemData();
            anX.unmarshal(byteBuffer);
            propulsionSystemData.add(anX);
        }

        for (int idx = 0; idx < ((Number) numberOfVectoringNozzleSystems).intValue(); idx++)
        {
            VectoringNozzleSystem anX = new VectoringNozzleSystem();
            anX.unmarshal(byteBuffer);
            vectoringSystemData.add(anX);
        }

    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = DistributedEmissionsRegenerationFamilyPdu.fromBufferToMap(byteBuffer);

    map.put("orginatingEntityID", EntityID.fromBufferToMap(byteBuffer));
    map.put("infraredSignatureRepresentationIndex", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("acousticSignatureRepresentationIndex", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("radarCrossSectionSignatureRepresentationIndex", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("numberOfPropulsionSystems", Short.toUnsignedInt(byteBuffer.getShort()));
    map.put("numberOfVectoringNozzleSystems", Short.toUnsignedInt(byteBuffer.getShort()));
    List propulsionSystemData = new ArrayList<>();
    for (int idx = 0; idx < ((Number) map.get("numberOfPropulsionSystems")).intValue(); idx++)
    {
        propulsionSystemData.add(PropulsionSystemData.fromBufferToMap(byteBuffer));
    }
    map.put("propulsionSystemData", propulsionSystemData);

    List vectoringSystemData = new ArrayList<>();
    for (int idx = 0; idx < ((Number) map.get("numberOfVectoringNozzleSystems")).intValue(); idx++)
    {
        vectoringSystemData.add(VectoringNozzleSystem.fromBufferToMap(byteBuffer));
    }
    map.put("vectoringSystemData", vectoringSystemData);

    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    DistributedEmissionsRegenerationFamilyPdu.fromMapToBuffer(map, byteBuffer);
    EntityID.fromMapToBuffer((PduMap) map.get("orginatingEntityID"), byteBuffer);
    byteBuffer.putShort(((Number) map.get("infraredSignatureRepresentationIndex")).shortValue());
    byteBuffer.putShort(((Number) map.get("acousticSignatureRepresentationIndex")).shortValue());
    byteBuffer.putShort(((Number) map.get("radarCrossSectionSignatureRepresentationIndex")).shortValue());
    byteBuffer.putShort(((Number) map.get("numberOfPropulsionSystems")).shortValue());
    byteBuffer.putShort(((Number) map.get("numberOfVectoringNozzleSystems")).shortValue());

    List propulsionSystemData = (List) map.get("propulsionSystemData");
    for (int idx = 0; idx < ((Number) map.get("numberOfPropulsionSystems")).intValue(); idx++)
    {
        PropulsionSystemData.fromMapToBuffer((PduMap) propulsionSystemData.get(idx), byteBuffer);
    }


    List vectoringSystemData = (List) map.get("vectoringSystemData");
    for (int idx = 0; idx < ((Number) map.get("numberOfVectoringNozzleSystems")).intValue(); idx++)
    {
        VectoringNozzleSystem.fromMapToBuffer((PduMap) vectoringSystemData.get(idx), byteBuffer);
    }

}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += DistributedEmissionsRegenerationFamilyPdu.getMarshalledSize(map);
    marshalSize += EntityID.getMarshalledSize((PduMap) map.get("orginatingEntityID"));
    marshalSize += 2;  // infraredSignatureRepresentationIndex
    marshalSize += 2;  // acousticSignatureRepresentationIndex
    marshalSize += 2;  // radarCrossSectionSignatureRepresentationIndex
    marshalSize += 2;  // numberOfPropulsionSystems
    marshalSize += 2;  // numberOfVectoringNozzleSystems
    List propulsionSystemData = (List) map.get("propulsionSystemData");
    for (int idx = 0; idx < ((Number) map.get("numberOfPropulsionSystems")).intValue(); idx++)
        marshalSize += PropulsionSystemData.getMarshalledSize((PduMap) propulsionSystemData.get(idx));
    List vectoringSystemData = (List) map.get("vectoringSystemData");
    for (int idx = 0; idx < ((Number) map.get("numberOfVectoringNozzleSystems")).intValue(); idx++)
        marshalSize += VectoringNozzleSystem.getMarshalledSize((PduMap) vectoringSystemData.get(idx));

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public synchronized boolean equalsImpl(Object obj)
 {
     final SEESPdu rhs = (SEESPdu)obj;

     if( ! Objects.equals(orginatingEntityID, rhs.orginatingEntityID) ) return false;
     if( ! (infraredSignatureRepresentationIndex == rhs.infraredSignatureRepresentationIndex)) return false;
     if( ! (acousticSignatureRepresentationIndex == rhs.acousticSignatureRepresentationIndex)) return false;
     if( ! (radarCrossSectionSignatureRepresentationIndex == rhs.radarCrossSectionSignatureRepresentationIndex)) return false;
     if( ! Objects.equals(propulsionSystemData, rhs.propulsionSystemData) ) return false;
     if( ! Objects.equals(vectoringSystemData, rhs.vectoringSystemData) ) return false;
    return super.equalsImpl(rhs);
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(super.toString());
    sb.append(" orginatingEntityID:").append(orginatingEntityID); // writeOneToString
    sb.append(" infraredSignatureRepresentationIndex:").append(infraredSignatureRepresentationIndex); // writeOneToString
    sb.append(" acousticSignatureRepresentationIndex:").append(acousticSignatureRepresentationIndex); // writeOneToString
    sb.append(" radarCrossSectionSignatureRepresentationIndex:").append(radarCrossSectionSignatureRepresentationIndex); // writeOneToString
    sb.append(" propulsionSystemData: ");
    propulsionSystemData.forEach(r->{ sb2.append(" ").append(r);}); // writeList
    sb.append(sb2.toString().trim());
    // https://stackoverflow.com/questions/2242471/clearing-a-string-buffer-builder-after-loop
    sb2.setLength(0); // reset
    sb.append(" vectoringSystemData: ");
    vectoringSystemData.forEach(r->{ sb2.append(" ").append(r);}); // writeList
    sb.append(sb2.toString().trim());
    // https://stackoverflow.com/questions/2242471/clearing-a-string-buffer-builder-after-loop
    sb2.setLength(0); // reset

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.orginatingEntityID,
	                     this.infraredSignatureRepresentationIndex,
	                     this.acousticSignatureRepresentationIndex,
	                     this.radarCrossSectionSignatureRepresentationIndex,
	                     this.numberOfPropulsionSystems,
	                     this.numberOfVectoringNozzleSystems,
	                     this.propulsionSystemData,
	                     this.vectoringSystemData);
 }
} // end of SEESPdu
