/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;
import edu.nps.moves.dis7.enumerations.*;
import com.google.common.primitives.*;
import com.google.common.base.Preconditions;
import java.nio.ByteBuffer;

/**
 * 5.5.5 Communicate information associated with one entity requesting a service from another.
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a> 
 */
public class ServiceRequestPdu extends LogisticsFamilyPdu implements Serializable, Marshaller
{

   /** The name of this PDU type */
   public static final String NAME = "ServiceRequestPdu";
   
   /** Entity that is requesting service (see 6.2.28), Section 7.4.2 */
   protected EntityID  requestingEntityID = new EntityID(); 

   /** Entity that is providing the service (see 6.2.28), Section 7.4.2 */
   protected EntityID  servicingEntityID = new EntityID(); 

   /** Type of service requested, Section 7.4.2 uid 63 */
   protected ServiceRequestServiceTypeRequested serviceTypeRequested = ServiceRequestServiceTypeRequested.values()[0];

   /** How many requested, Section 7.4.2 
   Value space: uint8 */
   protected int numberOfSupplyTypes;

   /** padding1 is an undescribed parameter...
   Value space: uint16 */
   protected int padding1 = (int) 0;

   /** supplies is an undescribed parameter... */
   protected List< SupplyQuantity > supplies = new ArrayList<>();
 

/** Constructor creates and configures a new instance object */
 public ServiceRequestPdu()
 {
    setPduType( DisPduType.SERVICE_REQUEST );
 }
/** copy method creates a deep copy of current object using preferred marshalling method
 * @return deep copy of PDU */
 public synchronized ServiceRequestPdu copy()
 {
     return copyDataOutputStream();
 }
/** Creates a "deep copy" of current object using ByteBuffer methods.
 * @return deep copy of PDU */
 public synchronized ServiceRequestPdu copyByteBuffer()
 {
     ServiceRequestPdu newCopy = new ServiceRequestPdu();
     ByteBuffer byteBuffer = ByteBuffer.allocate(400);
     try
     {
         this.marshal(byteBuffer);      // working
         newCopy.unmarshal(byteBuffer); // not working
     }
     catch (Exception e)
     {
         System.err.println("ServiceRequestPdu deep copy() marshall/unmarshall ByteBuffer exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
     return newCopy;
 }

/** byteArrayOutputStream (baos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
/** dataOutputStream (dos) is used for marshal/unmarshal serialization
   * @see copyDataOutputStream() */
protected DataOutputStream      dataOutputStream      = new DataOutputStream(byteArrayOutputStream);

/** copy method creates a deep copy of current object using DataOutputStream methods.
 * @return deep copy of PDU */
 public synchronized ServiceRequestPdu copyDataOutputStream()
 {
     ServiceRequestPdu newCopy = new ServiceRequestPdu();
     try
     {
         this.marshal(dataOutputStream);
         byte[] byteArrayDOS = byteArrayOutputStream.toByteArray();
         newCopy.unmarshal(ByteBuffer.wrap(byteArrayDOS));
     }
     catch (Exception e)
     {
         System.err.println("ServiceRequestPdu deep copy() marshall/unmarshall DataOutputStream exception " + e.getMessage());
         e.printStackTrace(System.err);
         System.exit(-1); // TODO: Abruptly ending VM not a good practice
     }
        try
        {
                 dataOutputStream.flush();
            byteArrayOutputStream.flush();
            byteArrayOutputStream.reset();
        }
        catch (IOException ioe)
        {
            System.err.println("ServiceRequestPdu copyDataOutputStream() flush IOException: " + ioe.getMessage());
        }
     return newCopy;
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
@Override
public synchronized int getMarshalledSize()
{
   int marshalSize = 0; 

   marshalSize = super.getMarshalledSize();
   if (requestingEntityID != null)
       marshalSize += requestingEntityID.getMarshalledSize();
   if (servicingEntityID != null)
       marshalSize += servicingEntityID.getMarshalledSize();
   if (serviceTypeRequested != null)
       marshalSize += serviceTypeRequested.getMarshalledSize();
   marshalSize += 1;  // numberOfSupplyTypes
   marshalSize += 2;  // padding1
   if (supplies != null)
       for (int idx=0; idx < supplies.size(); idx++)
       {
            SupplyQuantity listElement = supplies.get(idx);
            marshalSize += listElement.getMarshalledSize();
       }

   return marshalSize;
}


/** Setter for {@link ServiceRequestPdu#requestingEntityID}
  * @param pRequestingEntityID new value of interest
  * @return same object to permit progressive setters */
public synchronized ServiceRequestPdu setRequestingEntityID(EntityID pRequestingEntityID)
{
    requestingEntityID = pRequestingEntityID;
    return this;
}
/** Getter for {@link ServiceRequestPdu#requestingEntityID}
  * @return value of interest */
public EntityID getRequestingEntityID()
{
    return requestingEntityID;
}


/** Setter for {@link ServiceRequestPdu#servicingEntityID}
  * @param pServicingEntityID new value of interest
  * @return same object to permit progressive setters */
public synchronized ServiceRequestPdu setServicingEntityID(EntityID pServicingEntityID)
{
    servicingEntityID = pServicingEntityID;
    return this;
}
/** Getter for {@link ServiceRequestPdu#servicingEntityID}
  * @return value of interest */
public EntityID getServicingEntityID()
{
    return servicingEntityID;
}


/** Setter for {@link ServiceRequestPdu#serviceTypeRequested}
  * @param pServiceTypeRequested new value of interest
  * @return same object to permit progressive setters */
public synchronized ServiceRequestPdu setServiceTypeRequested(ServiceRequestServiceTypeRequested pServiceTypeRequested)
{
    serviceTypeRequested = pServiceTypeRequested;
    return this;
}
/** Getter for {@link ServiceRequestPdu#serviceTypeRequested}
  * @return value of interest */
public ServiceRequestServiceTypeRequested getServiceTypeRequested()
{
    return serviceTypeRequested; 
}

/** Setter for {@link ServiceRequestPdu#padding1}
  * @param pPadding1 new value of interest. Value space uint16
  * @return same object to permit progressive setters */
public synchronized ServiceRequestPdu setPadding1(int pPadding1)
{
    // Checking value is in value space uint16
    Preconditions.checkArgument(pPadding1 >= 0 && pPadding1 <= 65535, "Value outside valid value space");
    padding1 = pPadding1;
    return this;
}
/** Getter for {@link ServiceRequestPdu#padding1}
  * @return value of interest */
public int getPadding1()
{
    return padding1; 
}

/** Setter for {@link ServiceRequestPdu#supplies}
  * @param pSupplies new value of interest
  * @return same object to permit progressive setters */
public synchronized ServiceRequestPdu setSupplies(List<SupplyQuantity> pSupplies)
{
    supplies = pSupplies;
    return this;
}
/** Getter for {@link ServiceRequestPdu#supplies}
  * @return value of interest */
public List<SupplyQuantity> getSupplies()
{
    return supplies; 
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
@Override
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    super.marshal(dos);

    {
       requestingEntityID.marshal(dos);
       servicingEntityID.marshal(dos);
       serviceTypeRequested.marshal(dos);
       dos.writeByte(supplies.size());
       dos.writeShort((short) padding1);

       for (int idx = 0; idx < supplies.size(); idx++)
       {
            SupplyQuantity aSupplyQuantity = supplies.get(idx);
            aSupplyQuantity.marshal(dos);
       }

    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
@Override
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    uPosition += super.unmarshal(dis);


    {
        uPosition += requestingEntityID.unmarshal(dis);
        uPosition += servicingEntityID.unmarshal(dis);
        serviceTypeRequested = ServiceRequestServiceTypeRequested.unmarshalEnum(dis);
        uPosition += serviceTypeRequested.getMarshalledSize();
        numberOfSupplyTypes = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        padding1 = Short.toUnsignedInt(dis.readShort());
        uPosition += 2;
        for (int idx = 0; idx < ((Number) numberOfSupplyTypes).intValue(); idx++)
        {
            SupplyQuantity anX = new SupplyQuantity();
            uPosition += anX.unmarshal(dis);
            supplies.add(anX);
        }

    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   super.marshal(byteBuffer);
   requestingEntityID.marshal(byteBuffer);
   servicingEntityID.marshal(byteBuffer);
   serviceTypeRequested.marshal(byteBuffer);
   byteBuffer.put( (byte)supplies.size());
   byteBuffer.putShort((short) padding1);

   for (int idx = 0; idx < supplies.size(); idx++)
   {
        SupplyQuantity aSupplyQuantity = supplies.get(idx);
        aSupplyQuantity.marshal(byteBuffer);
   }

}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
@Override
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    super.unmarshal(byteBuffer);

    {
        requestingEntityID.unmarshal(byteBuffer);
        servicingEntityID.unmarshal(byteBuffer);
        serviceTypeRequested = ServiceRequestServiceTypeRequested.unmarshalEnum(byteBuffer);
        numberOfSupplyTypes = Byte.toUnsignedInt(byteBuffer.get());
        padding1 = Short.toUnsignedInt(byteBuffer.getShort());
        for (int idx = 0; idx < ((Number) numberOfSupplyTypes).intValue(); idx++)
        {
            SupplyQuantity anX = new SupplyQuantity();
            anX.unmarshal(byteBuffer);
            supplies.add(anX);
        }

    }
    return getMarshalledSize();
}


/**
 * Unpacks a Pdu into a PduMap from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception
{
    PduMap map;
    map = LogisticsFamilyPdu.fromBufferToMap(byteBuffer);

    map.put("requestingEntityID", EntityID.fromBufferToMap(byteBuffer));
    map.put("servicingEntityID", EntityID.fromBufferToMap(byteBuffer));
    map.put("serviceTypeRequested", ServiceRequestServiceTypeRequested.unmarshalEnum(byteBuffer).getValue());
    map.put("numberOfSupplyTypes", Byte.toUnsignedInt(byteBuffer.get()));
    map.put("padding1", Short.toUnsignedInt(byteBuffer.getShort()));
    List supplies = new ArrayList<>();
    for (int idx = 0; idx < ((Number) map.get("numberOfSupplyTypes")).intValue(); idx++)
    {
        supplies.add(SupplyQuantity.fromBufferToMap(byteBuffer));
    }
    map.put("supplies", supplies);

    return map;
}

/**
 * Packs a Pdu represented in map into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
{
    LogisticsFamilyPdu.fromMapToBuffer(map, byteBuffer);
    EntityID.fromMapToBuffer((PduMap) map.get("requestingEntityID"), byteBuffer);
    EntityID.fromMapToBuffer((PduMap) map.get("servicingEntityID"), byteBuffer);
    ServiceRequestServiceTypeRequested.getEnumForValue(((Number) map.get("serviceTypeRequested")).intValue()).marshal(byteBuffer);
    byteBuffer.put(((Number) map.get("numberOfSupplyTypes")).byteValue());
    byteBuffer.putShort(((Number) map.get("padding1")).shortValue());

    List supplies = (List) map.get("supplies");
    for (int idx = 0; idx < ((Number) map.get("numberOfSupplyTypes")).intValue(); idx++)
    {
        SupplyQuantity.fromMapToBuffer((PduMap) supplies.get(idx), byteBuffer);
    }

}

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   * @throws Exception   */
public static int getMarshalledSize(PduMap map) throws Exception
{
    int marshalSize = 0; 

    marshalSize += LogisticsFamilyPdu.getMarshalledSize(map);
    marshalSize += EntityID.getMarshalledSize((PduMap) map.get("requestingEntityID"));
    marshalSize += EntityID.getMarshalledSize((PduMap) map.get("servicingEntityID"));
    marshalSize += ServiceRequestServiceTypeRequested.getEnumForValue(((Number) map.get("serviceTypeRequested")).intValue()).getMarshalledSize();
    marshalSize += 1;  // numberOfSupplyTypes
    marshalSize += 2;  // padding1
    List supplies = (List) map.get("supplies");
    for (int idx = 0; idx < ((Number) map.get("numberOfSupplyTypes")).intValue(); idx++)
        marshalSize += SupplyQuantity.getMarshalledSize((PduMap) supplies.get(idx));

    return marshalSize;
}

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

@Override
 public synchronized boolean equalsImpl(Object obj)
 {
     final ServiceRequestPdu rhs = (ServiceRequestPdu)obj;

     if( ! Objects.equals(requestingEntityID, rhs.requestingEntityID) ) return false;
     if( ! Objects.equals(servicingEntityID, rhs.servicingEntityID) ) return false;
     if( ! (serviceTypeRequested == rhs.serviceTypeRequested)) return false;
     if( ! (padding1 == rhs.padding1)) return false;
     if( ! Objects.equals(supplies, rhs.supplies) ) return false;
    return super.equalsImpl(rhs);
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(super.toString());
    sb.append(" requestingEntityID:").append(requestingEntityID); // writeOneToString
    sb.append(" servicingEntityID:").append(servicingEntityID); // writeOneToString
    sb.append(" serviceTypeRequested:").append(serviceTypeRequested); // writeOneToString
    sb.append(" padding1:").append(padding1); // writeOneToString
    sb.append(" supplies: ");
    supplies.forEach(r->{ sb2.append(" ").append(r);}); // writeList
    sb.append(sb2.toString().trim());
    // https://stackoverflow.com/questions/2242471/clearing-a-string-buffer-builder-after-loop
    sb2.setLength(0); // reset

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
	 return Objects.hash(this.requestingEntityID,
	                     this.servicingEntityID,
	                     this.serviceTypeRequested,
	                     this.numberOfSupplyTypes,
	                     this.padding1,
	                     this.supplies);
 }
} // end of ServiceRequestPdu
