// autogenerated using string template disbitset1.txt

package edu.nps.moves.dis7.enumerations;

import edu.nps.moves.dis7.pdus.*;
import java.nio.ByteBuffer;


/**
 * Generated from XML,
 *  UID 229, marshal size 16,
 * ObjectStateAppearanceGeneral
 */
public class ObjectStateAppearanceGeneral extends DisBitSet 
{

  // autogenerated using string template disbitsetcomment.txt
  /**
   * (bit position 0, length=8) 8-bit unsigned integer indicating the percent completion of the object (0..100)
   */
  // autogenerated using string template disbitset15.txt
  public static Bits PERCENTCOMPLETE = new Bits(0, 8);

  // autogenerated using string template disbitsetcommentxref.txt
  /**
   * (bit position 8, length=2) Describes the damaged appearance,  use {@link AppearanceObjectGeneralDamage} values for this field
   */
  // autogenerated using string template disbitset16.txt
  public static Bits DAMAGE = new Bits(8, 2, AppearanceObjectGeneralDamage.class);

  // autogenerated using string template disbitsetcommentxref.txt
  /**
   * (bit position 10, boolean) Describes whether the object was predistributed,  use {@link AppearanceObjectGeneralPredistributed} values for this field
   */
  // autogenerated using string template disbitset16.txt
  public static Bits PREDISTRIBUTED = new Bits(10, 1, AppearanceObjectGeneralPredistributed.class);

  // autogenerated using string template disbitsetcommentxref.txt
  /**
   * (bit position 11, boolean) Describes the state of the object,  use {@link AppearanceEntityorObjectState} values for this field
   */
  // autogenerated using string template disbitset16.txt
  public static Bits STATE = new Bits(11, 1, AppearanceEntityorObjectState.class);

  // autogenerated using string template disbitsetcomment.txt
  /**
   * (bit position 12, boolean) Describes whether or not there is a smoke plume
   */
  // autogenerated using string template disbitset15.txt
  public static Bits ISSMOKING = new Bits(12, 1);

  // autogenerated using string template disbitsetcomment.txt
  /**
   * (bit position 13, boolean) Describes whether the object is burning and flames are visible
   */
  // autogenerated using string template disbitset15.txt
  public static Bits ISFLAMING = new Bits(13, 1);

  // autogenerated using string template disbitsetcommentxref.txt
  /**
   * (bit position 14, length=2) Describes whether the object has or contains an IED,  use {@link AppearanceObjectGeneralIEDPresent} values for this field
   */
  // autogenerated using string template disbitset16.txt
  public static Bits IEDPRESENT = new Bits(14, 2, AppearanceObjectGeneralIEDPresent.class);
  // autogenerated using string template disbitset2.txt
  /** Internal class */
  public static class Bits
  {
    private int position;
    private int length;
    private int inputmask;
    private Class cls;

    private Bits(int position) {
      this(position,1, null);
    }
    
    private Bits(int position, Class cls) {
      this(position,1, cls);
    }

    private Bits(int position, int length ) {
      this(position,length,null);
    }

    private Bits(int position, int length, Class cls) {
      this.position = position;
      this.length = length;
      this.cls = cls;
      inputmask = calculateMask(length);
    }
  }

  private static int BIT_LENGTH = 16; // length from bitfield element
  private static int BYTE_LENGTH = (BIT_LENGTH + Byte.SIZE - 1) / Byte.SIZE;

  /** Default constructor */
  public ObjectStateAppearanceGeneral()
  {
    super(BIT_LENGTH);
  }

  /** Default constructor with parameters
   * @param wh Bits custom data structure
   * @param value bits of interest  */
  public ObjectStateAppearanceGeneral(Bits wh, int value)
  {
    this();
    set(wh,value);
  }

  /** Accessor method to set value
   * @param wh Bits custom data structure
   * @param value bits of interest
   * @return this object */
  public ObjectStateAppearanceGeneral set(Bits wh, int value)
  {
    //if((value & ~wh.inputmask) != 0)
    //  throw new EnumNotFoundException("bad bits passed to "+getClass().getSimpleName()+", field "+wh.name() + " cannot be "+value);

    setbits(wh.position,wh.length,value);
    return this;
  }
/*
  public ObjectStateAppearanceGeneral set(Bits wh, Object val) throws Exception
  {
    if(val.getClass() != wh.cls)
      throw new EnumNotFoundException("bad enum passed to "+getClass().getSimpleName()+", field "+wh.name() + " cannot be "+val.getClass().getSimpleName());;
    Method getValueMethod = wh.cls.getMethod("getValue",null);
    int bits = (int)getValueMethod.invoke(val, (Object[])null);
    setbits(wh.position,wh.length,bits);
    return this;
  }
*/
  /** Some bitfields are defined without specific bits enumerated
   * @param start initial position in bit array
   * @param length number of bits
   * @param value bits of interest
   * @return this object */
  public ObjectStateAppearanceGeneral set(int start, int length, int value)
  {
      setbits(start,length,value);
      return this;
  }

  /** Provide string representation
   * @return string representation */
  @Override
  public String toString()
  {
      return "ObjectStateAppearanceGeneral: " + super.toString();
  }

  /**
   * Unmarshall raw value from byteBuffer. Unmarshalled number of bytes depends on bit set implementation.
   */
  public static int unmarshallRawValue(ByteBuffer byteBuffer) throws Exception
  {
      byte[] bytes = new byte[BYTE_LENGTH];
      byteBuffer.get(bytes);
      return bytesToInt(bytes);
  }

  /**
   * Marshall raw value to byteBuffer. Marshalled number of bytes depends on bit set implementation.
   */
  public static void marshallRawValue(int rawValue, ByteBuffer byteBuffer) throws Exception
  {
      byte[] bytes = intToBytes(rawValue, BYTE_LENGTH);
      byteBuffer.put(bytes);
  }

  /**
   * Get length of this bit set in bytes.
   */
  public static int getByteLength() {
      return BYTE_LENGTH;
  }

}
